<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 4               */
/* CACHE FILE: Generated: Wed, 29 Aug 2012 14:15:07 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_home_4 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['browse'] = array('canUploadToAlbum','canEditAlbum','canDeleteAlbum','showAlbumOptions','albumIsFriendOnly','albumIsPrivate','albumIsGlobal','hasLittleWeeBabbies','hasDescription','albumIsUploadable','albumIsNotContainer','albumsLoop','canIuploadDearSirWellCanI','browseIsDefault','hasName','catnorows');
$this->_funcHooks['home'] = array('hasUsers','hasOther','hasAnyone','isMember','recentAlbums','canIuploadDearSirWellCanI','globalAlbums','recentImages','activeAlbums','activeAlbums','hasPages','hasRecentAlbums','hasImages');


}

/* -- browse --*/
function browse($children, $album, $pages, $stats) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_home', $this->_funcHooks['browse'] ) )
{
$count_6710cdcf4ca0d59b19071da9fa691e06 = is_array($this->functionData['browse']) ? count($this->functionData['browse']) : 0;
$this->functionData['browse'][$count_6710cdcf4ca0d59b19071da9fa691e06]['children'] = $children;
$this->functionData['browse'][$count_6710cdcf4ca0d59b19071da9fa691e06]['album'] = $album;
$this->functionData['browse'][$count_6710cdcf4ca0d59b19071da9fa691e06]['pages'] = $pages;
$this->functionData['browse'][$count_6710cdcf4ca0d59b19071da9fa691e06]['stats'] = $stats;
}

if ( ! isset( $this->registry->templateStriping['browseRow'] ) ) {
$this->registry->templateStriping['browseRow'] = array( FALSE, "row1","row2 altrow");
}
$IPBHTML .= "<ul class='topic_buttons'>
	" . (($this->registry->gallery->helper('albums')->canCreate()) ? ("
		<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=post&amp;section=image", "public",'' ), "", "" ) . "'>{$this->lang->words['upload']}</a></li>
	") : ("")) . "
	" . (($this->settings['gallery_enable_both_views']) ? ("<li class='non_button'>
			" . (($this->settings['gallery_default_view'] == 'browse' && empty( $this->request['home'] )) ? ("
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;home=portal", "public",'' ), "false", "galleryportal" ) . "'>{$this->lang->words['home_ucfirst']}</a>
			") : ("
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery", "public",'' ), "false", "app=gallery" ) . "'>{$this->lang->words['home_ucfirst']}</a>
			")) . "
		</li>") : ("")) . "
</ul>
<h1 class='ipsType_pagetitle'>" . (($album['album_name']) ? ("{$album['album_name']}") : ("" . IPSLib::getAppTitle('gallery') . "")) . "</h1>
<br />
<div class='maintitle ipsFilterbar'>
	<ul class='ipsList_inline' style='display:inline'>
		<li " . ((( $this->request['sort_key'] == 'date' || !$this->request['sort_key'] ) && ( $this->request['sort_order'] == 'desc' || !$this->request['sort_order'] )) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;browseAlbum={$album['album_id']}&amp;dosort=1&amp;sort_key=date&amp;sort_order=desc&amp;filter_key={$this->request['filter_key']}", "public",'' ), "{$album['album_name_seo']}", "browsealbum" ) . "'>{$this->lang->words['filter_most_recent']}</a>
		</li>
		<li " . (($this->request['sort_key'] == 'rated' && $this->request['sort_order'] == 'desc') ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;browseAlbum={$album['album_id']}&amp;dosort=1&amp;sort_key=rated&amp;sort_order=desc&amp;filter_key={$this->request['filter_key']}", "public",'' ), "{$album['album_name_seo']}", "browsealbum" ) . "'>{$this->lang->words['filter_highest_rated']}</a>
		</li>
		<li " . (($this->request['sort_key'] == 'images' && $this->request['sort_order'] == 'desc') ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;browseAlbum={$album['album_id']}&amp;dosort=1&amp;sort_key=images&amp;sort_order=desc&amp;filter_key={$this->request['filter_key']}", "public",'' ), "{$album['album_name_seo']}", "browsealbum" ) . "'>{$this->lang->words['filter_most_images']}</a>
		</li>
		<li " . (($this->request['sort_key'] == 'comments' && $this->request['sort_order'] == 'desc') ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;browseAlbum={$album['album_id']}&amp;dosort=1&amp;sort_key=comments&amp;sort_order=desc&amp;filter_key={$this->request['filter_key']}", "public",'' ), "{$album['album_name_seo']}", "browsealbum" ) . "'>{$this->lang->words['filter_most_comments']}</a>
		</li>
	</ul>
	<ul class='ipsList_inline right' style='display:inline'>
		<li " . (($this->request['filter_key'] == 'all' || !$this->request['filter_key']) ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;browseAlbum={$album['album_id']}&amp;dosort=1&amp;sort_key=date&amp;sort_order=desc&amp;filter_key=all", "public",'' ), "{$album['album_name_seo']}", "browsealbum" ) . "'>{$this->lang->words['filter_show_all']}</a>
		</li>
		<li " . (($this->request['filter_key'] == 'global') ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;browseAlbum={$album['album_id']}&amp;dosort=1&amp;sort_key=date&amp;sort_order=desc&amp;filter_key=global", "public",'' ), "{$album['album_name_seo']}", "browsealbum" ) . "'>{$this->lang->words['filter_show_global']}</a>
		</li>
		<li " . (($this->request['filter_key'] == 'member') ? ("class='active'") : ("")) . ">
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;browseAlbum={$album['album_id']}&amp;dosort=1&amp;sort_key=date&amp;sort_order=desc&amp;filter_key=member", "public",'' ), "{$album['album_name_seo']}", "browsealbum" ) . "'>{$this->lang->words['filter_show_member']}</a>
		</li>
	</ul>
</div>
" . ((!count($children)) ? ("
	<div class='no_messages'>
		{$this->lang->words['albums_none_to_see']}
	</div>
") : ("
	<div class='ipsBox'>
		<div class='ipsBox_container'>
			<table class='ipb_table'>
								".$this->__f__85c5395390e291baf1d55d63b7560ea6($children,$album,$pages,$stats)."			</table>
		</div>
	</div>		
")) . "
<br />
" . (($pages) ? ("
	{$pages}
	<br />
") : ("")) . "
<br />
<div id='board_stats'>
	<ul class='ipsType_small ipsList_inline'>
		<li class='clear'>
			<span class='value'>{$stats['albums']}</span>
			{$this->lang->words['stats_total_albums']}
		</li>
		<li class='clear'>
			<span class='value'>{$stats['images']}</span>
			{$this->lang->words['stats_total_images']}
		</li>
		<li class='clear'>
			<span class='value'>{$stats['comments']}</span>
			{$this->lang->words['stats_total_comments']}
		</li>
		<li class='clear'>
			<span class='value'>{$stats['diskspace']}</span>
			{$this->lang->words['stats_total_size']}
		</li>
	</ul>
</div>
<br />";
return $IPBHTML;
}


function __f__85c5395390e291baf1d55d63b7560ea6($children, $album, $pages, $stats)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $children as $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					<tr class='" .  IPSLib::next( $this->registry->templateStriping["browseRow"] ) . "'>
						<td class='col_c_icon'>" . $this->registry->getClass('gallery')->inlineResize( $data['thumb'],'thumb_medium','','' ) . "</td>
						<td>
							" . (($this->registry->gallery->helper('albums')->isUploadable($data) || $this->registry->gallery->helper('albums')->isOwner($data) || $this->registry->gallery->helper('albums')->canModerate($data)) ? ("<ul class='ipsList_inline right'>
									" . (($this->registry->gallery->helper('albums')->isUploadable($data)) ? ("
										<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=post&amp;section=image&amp;album_id={$data['album_id']}", "public",'' ), "", "" ) . "' title='{$this->lang->words['upload']}' class='ipsButton_secondary'>" . $this->registry->getClass('output')->getReplacement("gallery_image") . "</a></li>
									") : ("")) . "
									" . (($this->registry->gallery->helper('albums')->canEdit($data)) ? ("
										<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;albumedit={$data['album_id']}", "public",'' ), "{$data['album_name_seo']}", "editalbum" ) . "' class='ipsButton_secondary' title='{$this->lang->words['edit']}'>" . $this->registry->getClass('output')->getReplacement("galery_album_edit") . "</a></li>
									") : ("")) . "
									" . (((!$this->registry->gallery->helper('albums')->isGlobal($data) && $this->registry->gallery->helper('albums')->canDelete($data))) ? ("
										<li><a href=\"javascript:void(0);\" album-id=\"{$data['album_id']}\" class=\"_albumDelete ipsButton_secondary\" title='{$this->lang->words['delete_link']}'>" . $this->registry->getClass('output')->getReplacement("gallery_album_delete") . "</a></li>
									") : ("")) . "
								</ul>") : ("")) . "
							" . (($this->registry->gallery->helper('albums')->isFriends($data)) ? ("
								<span class='ipsBadge ipsBadge_green reset_cursor' data-tooltip='{$this->lang->words['friend_only_prefix_desc']}' title='{$this->lang->words['friend_only_prefix_desc']}'>{$this->lang->words['friend_only_prefix']}</span>&nbsp;
							") : ("")) . "
							" . (($this->memberData['g_album_private'] && $this->registry->gallery->helper('albums')->isPrivate($data)) ? ("
								<span class='ipsBadge ipsBadge_red reset_cursor'>{$this->lang->words['private_ucfirst']}</span>&nbsp;
							") : ("")) . "
							" . (($this->request['filter_key'] != 'global' && $this->registry->gallery->helper('albums')->isGlobal($data)) ? ("
								<span class='ipsBadge ipsBadge_grey reset_cursor'>{$this->lang->words['global_prefix']}</span>&nbsp;
							") : ("")) . "
							<strong>
								{$data['depthString']}
								" . (($data['_childrenCount']) ? ("
									<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;album={$data['album_id']}&amp;display=detail", "public",'' ), "{$data['album_name_seo']}", "viewalbum" ) . "' title='" . sprintf( $this->lang->words['view_child_albums'], $data['_childrenCount'] ) . "'>{$data['album_name']}</a>
								") : ("
									<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;album={$data['album_id']}", "public",'' ), "{$data['album_name_seo']}", "viewalbum" ) . "'>{$data['album_name']}</a>
								")) . "
							</strong>
							
							" . (($data['album_description']) ? ("
								<div class='album_desc'>
									" . IPSText::truncate( strip_tags( IPSText::getTextClass('bbcode')->stripAllTags( $data['album_description'] ), '<br />' ), 200 ) . "
								</div>
							") : ("")) . "
						</td>
						<td class='col_c_post desc'>
							" . ((!$this->registry->gallery->helper('albums')->isContainerOnly($data)) ? ("<strong>{$data['album_count_imgs']}" . (($data['mod_images']) ? (" <em class='moderated inline-moderated'>(+ {$data['mod_images']} {$this->lang->words['queued_suffix']})</em>") : ("")) . "</strong> {$this->lang->words['images']}<br />
								<strong>{$data['album_count_comments']}" . (($data['mod_comments']) ? (" <em class='moderated inline-moderated'>(+ {$data['mod_comments']} {$this->lang->words['queued_suffix']})</em>") : ("")) . "</strong> {$this->lang->words['comments']}
								" . (($this->registry->gallery->helper('albums')->isUploadable($data)) ? ("
									<br /><br />{$this->lang->words['last_upload']}: " . $this->registry->getClass('class_localization')->getDate($data['album_last_img_date'],"DATE", 0) . "
								") : ("")) . "") : ("")) . "
						</td>
					</tr>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- home --*/
function home($feature, $sidebars, $albums, $pages='', $stats) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_home', $this->_funcHooks['home'] ) )
{
$count_d950630659e11622ec0ed74695a6a52e = is_array($this->functionData['home']) ? count($this->functionData['home']) : 0;
$this->functionData['home'][$count_d950630659e11622ec0ed74695a6a52e]['feature'] = $feature;
$this->functionData['home'][$count_d950630659e11622ec0ed74695a6a52e]['sidebars'] = $sidebars;
$this->functionData['home'][$count_d950630659e11622ec0ed74695a6a52e]['albums'] = $albums;
$this->functionData['home'][$count_d950630659e11622ec0ed74695a6a52e]['pages'] = $pages;
$this->functionData['home'][$count_d950630659e11622ec0ed74695a6a52e]['stats'] = $stats;
}
$IPBHTML .= "<ul class='topic_buttons'>
	" . (($this->registry->gallery->helper('albums')->canCreate()) ? ("
		<li><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;module=post&amp;section=image", "public",'' ), "", "" ) . "'>{$this->lang->words['upload']}</a></li>
	") : ("")) . "
	" . (($this->settings['gallery_enable_both_views']) ? ("
		<li class='non_button'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;browseAlbum=0", "public",'' ), "false", "browsealbumroot" ) . "'>{$this->lang->words['gbutton_browse']}</a></li>
	") : ("")) . "
</ul>
<br />
<div class='ipsLayout'>
	<div class='ipsLayout_right'>
		<!--" . ((is_array($sidebars['globalAlbums'])) ? ("
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_albums'), 'miniAlbumStripHorizontal' ) ? $this->registry->getClass('output')->getTemplate('gallery_albums')->miniAlbumStripHorizontal($sidebars['globalAlbums'], $this->lang->words['home_active_global_albums']) : '' ) . "
			<br />
		") : ("")) . "-->
		<!--" . (($sidebars['recentImages']) ? ("
			<div class='general_box'>
				<h3>{$this->lang->words['home_recent_images']}</h3>
				<ul class='ipsPad_half short ipsList_inline ipsList_reset' id='home_side_recents'>
					".$this->__f__1309a6b6db2b2ce5c11b0a9955e6e33a($feature,$sidebars,$albums,$pages,$stats)."				</ul>
			</div>
			<br />
		") : ("")) . "-->
		<!-- " . (($sidebars['recentComments']) ? ("
			" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_albums'), 'miniLatestCommentBlock' ) ? $this->registry->getClass('output')->getTemplate('gallery_albums')->miniLatestCommentBlock($sidebars['recentComments'], $this->lang->words['home_recent_comments']) : '' ) . "
			<br />
		") : ("")) . "-->
		" . ((is_array($sidebars['activeAlbums']) && count($sidebars['activeAlbums'])) ? ("
			<div class='general_box'>
				<h3>{$this->lang->words['home_active_albums']}</h3>
				<ul>
					".$this->__f__c48089aace2b3b8cf6216d1a064b6850($feature,$sidebars,$albums,$pages,$stats)."				</ul>
			</div>
		") : ("")) . "
	</div>
	<div class='ipsLayout_content'>
		<div class='ipsBox'>
			<div class='ipsBox_container ipsPad short'>
				" . (($feature['id']) ? ("
					<div id=\"image_wdesc_{$feature['id']}\">
						{$feature['tag']}
						<p id=\"image_wdesc_{$feature['id']}_description\" class='imageDescription' style=\"display:none;\"><strong>{$feature['caption']}</strong><br />{$feature['description']}<br />{$this->lang->words['from_album']}: {$feature['album_name']}</p>
					</div>
				
					<script type=\"text/javascript\">
						document.observe(\"dom:loaded\", function(){
							ipb.gallery.registerDescription({$feature['id']});
						} );
					</script>
					<br />
				") : ("")) . "
				" . ((is_array( $albums ) && count( $albums )) ? ("<a id='recentalbums'></a>
					<div class='ipsPad'>
						<h2 class='ipsType_subtitle'>{$this->lang->words['home_recent_albums']}</h2><br />
						<ul id='home_recent_albums' class='ipsList_inline ipsList_reset short'>
						".$this->__f__a31c4f4cd39b4b31692e577693cc1080($feature,$sidebars,$albums,$pages,$stats)."						</ul>
						" . ((! empty( $pages )) ? ("
							<div class='ipsPad clearfix'>{$pages}</div>
						") : ("")) . "
					</div>") : ("")) . "
			</div>
		</div>
	</div>
</div>
<script type=\"text/javascript\">
	var st = " . intval($this->request['st']) . ";
	if ( st > 0 )
	{
		$('recentalbums').scrollTo();
	}
</script>
<br class='clear' />
<br />
<div id='board_stats'>
	<ul class='ipsType_small ipsList_inline'>
		<li class='clear'>
			<span class='value'>" . $this->registry->getClass('class_localization')->formatNumber( $stats['albums'] ) . "</span>
			{$this->lang->words['stats_total_albums']}
		</li>
		<li class='clear'>
			<span class='value'>" . $this->registry->getClass('class_localization')->formatNumber( $stats['images'] ) . "</span>
			{$this->lang->words['stats_total_images']}
		</li>
		<li class='clear'>
			<span class='value'>" . $this->registry->getClass('class_localization')->formatNumber( $stats['comments'] ) . "</span>
			{$this->lang->words['stats_total_comments']}
		</li>
		" . (($stats['images']) ? ("
		<li class='clear'>
			<span class='value'>{$stats['diskspace']}</span>
			{$this->lang->words['stats_total_size']}
		</li>
		") : ("")) . "
	</ul>
</div>
<br />";
return $IPBHTML;
}


function __f__1309a6b6db2b2ce5c11b0a9955e6e33a($feature, $sidebars, $albums, $pages='', $stats)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $sidebars['recentImages'] as $id => $image )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							<li class='gallery_tiny_box' -data-id=\"{$id}\">
								" . $this->registry->getClass('gallery')->inlineResize( $image['thumb'],'thumb_small','','' ) . "
							</li>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__c48089aace2b3b8cf6216d1a064b6850($feature, $sidebars, $albums, $pages='', $stats)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $sidebars['activeAlbums'] as $i => $album )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<li class='" .  IPSLib::next( $this->registry->templateStriping["activeAlbums"] ) . " clear'>
							<div class='album horizontal'>
								" . $this->registry->getClass('gallery')->inlineResize( $album['album']['thumb'],'thumb_small','','' ) . "
								<p><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;album={$album['album']['album_id']}", "public",'' ), "{$album['album']['album_name_seo']}", "viewalbum" ) . "'>{$album['album']['album_name']}</a></p>
								<div style='padding-top:5px'>
									" . ((count($album['users']) OR $album['others']) ? ("<span class='desc'>{$this->lang->words['browsing_ucfirst']}:</span>
										" . ((count($album['users'])) ? ("
											" . implode( ", ", $album['users']) . "
										") : ("")) . "
										" . (($album['others']) ? ("
											<span class=\"desc\">({$album['others']} {$this->lang->words['others_lower']})</span>
										") : ("")) . "") : ("")) . "
								</div>
							</div>
						</li>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__a31c4f4cd39b4b31692e577693cc1080($feature, $sidebars, $albums, $pages='', $stats)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $albums as $id => $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							<li>
								" . $this->registry->getClass('gallery')->inlineResize( $data['thumb'],'thumb_medium','','' ) . "
								<div class='desc ipsType_smaller homepage'>
									<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;album={$data['album_id']}", "public",'' ), "{$data['album_name_seo']}", "viewalbum" ) . "'>{$data['album_name']}</a>
									" . (($data['member_id']) ? ("<br />{$this->lang->words['by_ucfirst']}: " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($data) : '' ) . "") : ("<br />&nbsp;")) . "
								</div>
							</li>
						
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>