<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 4               */
/* CACHE FILE: Generated: Wed, 29 Aug 2012 14:15:07 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_mod_4 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['mergePostForm'] = array('selectedpids','selectedpidsjs','dates','authors','uploads','mergepostsdates','mergepostsauthors','mergepostsattachments');
$this->_funcHooks['movePostForm'] = array('isGuest','posts','movepostserror','movepostsloop');
$this->_funcHooks['moveTopicsForm'] = array('topics','movetopicsloop');
$this->_funcHooks['pruneSplash'] = array('defaultselectedoption','types','prunecompletehtml','confirmprune');
$this->_funcHooks['splitPostForm'] = array('split_posts','splitpostsloop');
$this->_funcHooks['topicHistory'] = array('mod_logs','topicmodlogs');


}

/* -- deleteTopicForm --*/
function deleteTopicForm($forum, $topic) {
$IPBHTML = "";
$IPBHTML .= "<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=moderate&amp;section=moderate", "public",'' ), "", "" ) . "' method='post'>
<input type='hidden' name='auth_key' value='{$this->member->form_hash}' />
<input type='hidden' name='do' value='08' />
<input type='hidden' name='t' value='{$topic['tid']}' />
<input type='hidden' name='f' value='{$forum['id']}' />
<input type='hidden' name='st' value='{$this->request['st']}' />
<input type='hidden' name='return' value='{$this->request['return']}' />
<h2 class='maintitle'>{$this->lang->words['top_delete']}: {$forum['name']} -&gt; {$topic['title']}</h2>
<div class='generic_bar'></div>
<div class='post_form'>
	<p class='row1 field'>{$this->lang->words['delete_topic']}</p>
	<fieldset class='submit'>
		<input type=\"submit\" class='input_submit' value=\"{$this->lang->words['submit_delete']}\" /> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$topic['tid']}&amp;st={$this->request['st']}", "public",'' ), "{$topic['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
	</fieldset>
</div>
</form>";
return $IPBHTML;
}

/* -- editTopicTitle --*/
function editTopicTitle($forum, $topic) {
$IPBHTML = "";
$IPBHTML .= "<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=moderate&amp;section=moderate", "public",'' ), "", "" ) . "' method='post'>
<input type='hidden' name='auth_key' value='{$this->member->form_hash}' />
<input type='hidden' name='do' value='12' />
<input type='hidden' name='t' value='{$topic['tid']}' />
<input type='hidden' name='f' value='{$forum['id']}' />
<input type='hidden' name='st' value='{$this->request['st']}' />
<h2 class='maintitle'>{$this->lang->words['top_edit']}: {$forum['name']} &gt; {$topic['title']}</h2>
<div class='generic_bar'></div>
<div class='post_form'>
	<fieldset>
		<h3 class='bar'>{$this->lang->words['editing_topic_title']}</h3>
		<ul>
			<li class='field'>
				<label for='topic_title'>{$this->lang->words['edit_f_title']}</label>
				<input class='input_text' type=\"text\" size=\"40\" id='topic_title' maxlength=\"{$this->settings['topic_title_max_len']}\" name=\"TopicTitle\" value=\"{$topic['title']}\" />
			</li>
		</ul>
	</fieldset>
	<fieldset class='submit'>
		<input type=\"submit\" class='input_submit' value=\"{$this->lang->words['submit_edit']}\" /> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$topic['tid']}", "public",'' ), "{$topic['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
	</fieldset>
</div>
</form>
<br />";
return $IPBHTML;
}

/* -- mergeMultiplePolls --*/
function mergeMultiplePolls($polls, $tids) {
$IPBHTML = "";
$IPBHTML .= "<h1 class='ipsType_pagetitle'>{$this->lang->words['poll_merge_title']}</h1>
<br />
<div class='message'>
	{$this->lang->words['poll_merge_blurb']}
</div>
<br />".$this->__f__1d6a37a27b8a674ed810ecc089567206($polls,$tids)."";
return $IPBHTML;
}


function __f__5b406888de7d779a2cbc855f715abcb4($polls, $tids,$poll='',$questionID='',$questionData='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $questionData['choice'] as $choiceID => $name )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<li>
							<span class='answer'>{$name}</span>
							<span class='votes'>({$questionData['votes'][$choiceID]} {$this->lang->words['poll_votes']})</span>
						</li>	
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__e64730a959a46009688ea79783bac350($polls, $tids,$poll='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( unserialize( stripslashes( $poll['choices'] ) ) as $questionID => $questionData )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<div class='poll_question'>
				<h4 class='rounded'>{$questionData['question']}</h4>
				<ol>
					".$this->__f__5b406888de7d779a2cbc855f715abcb4($polls,$tids,$poll,$questionID,$questionData)."				</ol>
			</div>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__1d6a37a27b8a674ed810ecc089567206($polls, $tids)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $polls as $poll )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<div class='general_box alt poll'>
		<h3>{$poll['poll_question']}</h3>
		".$this->__f__e64730a959a46009688ea79783bac350($polls,$tids,$poll)."		<fieldset class='submit'>
			<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=moderate&amp;section=moderate&amp;do=topicchoice&amp;tact=merge&amp;selectedtids={$tids}&amp;f={$this->request['f']}&amp;chosenpolltid={$poll['tid']}&amp;auth_key={$this->member->form_hash}", "public",'' ), "", "" ) . "' class='ipsButton'>{$this->lang->words['poll_merge_submit']}</a>
		</fieldset>
	</div>
	<br /><br />

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- mergePostForm --*/
function mergePostForm($editor, $dates, $authors, $uploads, $seoTitle) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_mod', $this->_funcHooks['mergePostForm'] ) )
{
$count_adcf0e78a09ce8a91a8ad68e630e166c = is_array($this->functionData['mergePostForm']) ? count($this->functionData['mergePostForm']) : 0;
$this->functionData['mergePostForm'][$count_adcf0e78a09ce8a91a8ad68e630e166c]['editor'] = $editor;
$this->functionData['mergePostForm'][$count_adcf0e78a09ce8a91a8ad68e630e166c]['dates'] = $dates;
$this->functionData['mergePostForm'][$count_adcf0e78a09ce8a91a8ad68e630e166c]['authors'] = $authors;
$this->functionData['mergePostForm'][$count_adcf0e78a09ce8a91a8ad68e630e166c]['uploads'] = $uploads;
$this->functionData['mergePostForm'][$count_adcf0e78a09ce8a91a8ad68e630e166c]['seoTitle'] = $seoTitle;
}

$selectedPids	= implode( ',', $this->request['selectedpids'] );
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("moderate", "0" ) . "
<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=moderate&amp;section=moderate", "public",'' ), "", "" ) . "' method='post'>
<input type='hidden' name='auth_key' value='{$this->member->form_hash}' />
<input type='hidden' name='do' value='postchoice' />".$this->__f__95bfef142bae810588fcd76cf7447bb9($editor,$dates,$authors,$uploads,$seoTitle)."" . (($this->request['selectedpidsJS']) ? ("".$this->__f__bffb22b7996f11151d6587164bfe722a($editor,$dates,$authors,$uploads,$seoTitle)."") : ("")) . "
<input type=\"hidden\" name=\"t\" value=\"{$this->request['t']}\" />
<input type=\"hidden\" name=\"f\" value=\"{$this->request['f']}\" />
<input type='hidden' name='tact' value='merge' />
<input type='hidden' name='checked' value='1' />
<input type='hidden' name='st' value='{$this->request['st']}' />
<p class='message'>{$this->lang->words['merge_select']}</p>
<br />
<h2 class='maintitle'>{$this->lang->words['cm_title']}</h2>
<div class='generic_bar'></div>
<div class='post_form'>
	<fieldset>
		<h3 class='bar'>{$this->lang->words['post_options']}</h3>
		<ul>
			<li class='field'>
				<label for='post_date'>{$this->lang->words['cm_post']}</label>
				<select name=\"postdate\" class=\"input_select\" id='post_date'>
					" . ((is_array($dates) AND count($dates)) ? ("
						".$this->__f__22a9f0e0ee452fa19855392cff301502($editor,$dates,$authors,$uploads,$seoTitle)."					") : ("")) . "
				</select>
			</li>
			<li class='field'>
				<label for='post_author'>{$this->lang->words['cm_author']}</label>
				<select name=\"postauthor\" class=\"input_select\" id='post_author'>
					" . ((is_array($authors) AND count($authors)) ? ("
						".$this->__f__b3e61cc8e6cce132d06b2ce3894ca93e($editor,$dates,$authors,$uploads,$seoTitle)."					") : ("")) . "
				</select>
			</li>
		</ul>
		<h3 class='bar'>{$this->lang->words['post_content']}</h3>
		{$editor}
	</fieldset>
	" . ((count($uploads)) ? ("
		<fieldset>
			<h3 class='bar'>{$this->lang->words['cm_attach']}</h3>
			<h4>{$this->lang->words['cm_attach2']}<h4>
			<table>
				".$this->__f__7993b9b2774af206d23dad59154fb2a3($editor,$dates,$authors,$uploads,$seoTitle)."			</table>
		</fieldset>
	") : ("")) . "
	<fieldset class='submit'>
				<input type=\"submit\" class='input_submit' value=\"{$this->lang->words['cm_submit']}\" /> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$this->request['t']}&amp;selectedpids={$selectedPids}", "public",'' ), "{$seoTitle}", "showtopic" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
	</fieldset>
</div>
</form>";
return $IPBHTML;
}


function __f__95bfef142bae810588fcd76cf7447bb9($editor, $dates, $authors, $uploads, $seoTitle)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $this->request['selectedpids'] as $pid )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<input type=\"hidden\" name=\"selectedpids[{$pid}]\" value=\"{$pid}\" />

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__bffb22b7996f11151d6587164bfe722a($editor, $dates, $authors, $uploads, $seoTitle)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( explode( ',', $this->request['selectedpidsJS'] ) as $pid )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<input type=\"hidden\" name=\"selectedpids[{$pid}]\" value=\"{$pid}\" />
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__22a9f0e0ee452fa19855392cff301502($editor, $dates, $authors, $uploads, $seoTitle)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $dates as $date )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							<option value='{$date[0]}'>{$date[1]}</option>
						
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__b3e61cc8e6cce132d06b2ce3894ca93e($editor, $dates, $authors, $uploads, $seoTitle)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $authors as $author )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							<option value='{$author[0]}'>{$author[1]}</option>
						
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__7993b9b2774af206d23dad59154fb2a3($editor, $dates, $authors, $uploads, $seoTitle)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $uploads as $attach )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					<tr>
						<td width=\"1%\">
							<select name=\"attach_{$attach['attach_id']}\" class=\"input_select\">
								<option value=\"keep\">{$this->lang->words['cm_keep']}</option>
								<option value=\"delete\">{$this->lang->words['cm_delete']}</option>
							</select>
						</td>
						<td width=\"1%\"><img src=\"{$this->settings['public_dir']}{$attach['image']}\" alt=\"{$this->lang->words['cm_attach_alt']}\" /></td>
						<td width=\"15%\" nowrap=\"nowrap\">{$attach['size']}</td>
						<td width=\"95%\"><a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=attach&amp;section=attach&amp;attach_id={$attach['attach_id']}", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['cm_attach_title']}\">{$attach['attach_file']}</a> #{$attach['attach_rel_id']}</td>
					</tr>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- mergeTopicsForm --*/
function mergeTopicsForm($forum, $topic) {
$IPBHTML = "";
$IPBHTML .= "<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=moderate&amp;section=moderate", "public",'' ), "", "" ) . "' method='post'>
<input type='hidden' name='auth_key' value='{$this->member->form_hash}' />
<input type='hidden' name='do' value='61' />
<input type='hidden' name='t' value='{$topic['tid']}' />
<input type='hidden' name='f' value='{$forum['id']}' />
<input type='hidden' name='st' value='{$this->request['st']}' />
<h2 class='maintitle'>{$this->lang->words['mt_top']}: {$forum['name']} &gt; {$topic['title']}</h2>
<div class='generic_bar'></div>
<div class='post_form'>
	<fieldset>
		<h3 class='bar'>{$this->lang->words['merge_topic_options']}</h3>
		<ul>
			<li class='field'>
				<label for='new_title'>{$this->lang->words['mt_new_title']}</label>
				<input type=\"text\" id='new_title' class='input_text' size=\"40\" maxlength=\"250\" name=\"title\" value=\"{$topic['title']}\" />
			</li>
			<li class='field'>
				<label for='topic_url'>{$this->lang->words['mt_tid']}</label>
				<input type=\"text\" id='topic_url' class='input_text' size=\"40\" name=\"topic_url\" value=\"\" />
				<span class='desc'>{$this->lang->words['mt_tid_desc']}</span>
			</li>
		</ul>
	</fieldset>
	<fieldset class='submit'>
		<input type=\"submit\" class='input_submit' value=\"{$this->lang->words['mt_submit']}\" /> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$topic['tid']}", "public",'' ), "{$topic['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
	</fieldset>
</div>
</form>";
return $IPBHTML;
}

/* -- movePostForm --*/
function movePostForm($forum, $topic, $posts, $error='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_mod', $this->_funcHooks['movePostForm'] ) )
{
$count_59bef8924b8b14e4596350f8db541eb7 = is_array($this->functionData['movePostForm']) ? count($this->functionData['movePostForm']) : 0;
$this->functionData['movePostForm'][$count_59bef8924b8b14e4596350f8db541eb7]['forum'] = $forum;
$this->functionData['movePostForm'][$count_59bef8924b8b14e4596350f8db541eb7]['topic'] = $topic;
$this->functionData['movePostForm'][$count_59bef8924b8b14e4596350f8db541eb7]['posts'] = $posts;
$this->functionData['movePostForm'][$count_59bef8924b8b14e4596350f8db541eb7]['error'] = $error;
}

$selectedPids	= implode( ',', $this->request['selectedpids'] );
$IPBHTML .= "" . (($error) ? ("
	<p class=\"message error\">{$error}</p>
") : ("")) . "
" . $this->registry->getClass('output')->addJSModule("moderate", "0" ) . "
<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=moderate&amp;section=moderate", "public",'' ), "", "" ) . "' method='post'>
<input type='hidden' name='auth_key' value='{$this->member->form_hash}' />
<input type='hidden' name='do' value='postchoice' />
<input type='hidden' name='t' value='{$topic['tid']}' />
<input type='hidden' name='f' value='{$forum['id']}' />
<input type='hidden' name='tact' value='move' />
<input type='hidden' name='checked' value='1' />
<input type='hidden' name='st' value='{$this->request['st']}' />
<h2 class='maintitle'>{$this->lang->words['cmp_title']}: {$forum['name']} -&gt; {$topic['title']}</h2>
<div class='ipsBox clearfix'>
	<div class='ipsBox_container'>
		<ul>
			<li class='field'>
				<label for='topic_url'>{$this->lang->words['cmp_topic']}</label>
				<input type=\"text\" size=\"50\" name=\"topic_url\" value=\"\" id='topic_url' class='input_text' />
				<span class='desc'>{$this->lang->words['cmp_topic2']}</span>
			</li>
		</ul>
	</div>
</div>
<br />
<h2 class='maintitle'>{$this->lang->words['move_topic_summary']}</h2>
<div class='ipsBox clearfix'>
	<div class='ipsBox_container'>
		" . ((is_array( $posts ) AND count( $posts )) ? ("
			".$this->__f__57e9fb00b8c0acb58344f5c810378ac0($forum,$topic,$posts,$error)."		") : ("")) . "
	</div>
</div>
<fieldset class='submit'>
		<input type=\"submit\" name=\"submit\" class='input_submit' value=\"{$this->lang->words['cmp_submit']}\" /> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$topic['tid']}&amp;selectedpids={$selectedPids}", "public",'' ), "{$topic['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
</fieldset>
</form>";
return $IPBHTML;
}


function __f__57e9fb00b8c0acb58344f5c810378ac0($forum, $topic, $posts, $error='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $posts as $row )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<div class='post_block no_sidebar topic_summary'>
					<div class='post_wrap'>
					<h3 class='row2" . ((empty($row['member_id'])) ? (" guest") : ("")) . "'><input type='checkbox' id='checkbox_{$row['pid']}' name='selectedpids[{$row['pid']}]' value='{$row['pid']}' class='post_mod' checked='checked' /> {$row['author_name']}</h3>
					<div class='post_body'>
						<p class='posted_info'><label for='checkbox_{$row['pid']}' class='post_mod hide'>{$this->lang->words['st_split']}</label> {$this->lang->words['move_posted']} {$row['date']}</p>
						<div class='post'>{$row['post']}</div>
					</div>
				</div>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- moveTopicForm --*/
function moveTopicForm($forum, $topic, $forum_jump) {
$IPBHTML = "";
$IPBHTML .= "<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=moderate&amp;section=moderate", "public",'' ), "", "" ) . "' method='post'>
<input type='hidden' name='auth_key' value='{$this->member->form_hash}' />
<input type='hidden' name='do' value='14' />
<input type='hidden' name='t' value='{$topic['tid']}' />
<input type='hidden' name='f' value='{$forum['id']}' />
<input type='hidden' name='st' value='{$this->request['st']}' />

<p class='message'>{$this->lang->words['move_exp']}</p>
<br />
<h2 class='maintitle'>{$this->lang->words['top_move']}: {$forum['name']} &gt; {$topic['title']}</h2>
<div class='generic_bar'></div>
<div class='post_form'>
	<fieldset>
		<h3 class='bar'>{$this->lang->words['move_topic_options']}</h3>
		<ul>
			<li class='field'>
				<label for='move_from'>{$this->lang->words['move_from']} <strong>{$forum['name']}</strong> {$this->lang->words['to']}</label>
				<select name=\"move_id\" id='move_from' class='input_select'>{$forum_jump}</select>
			</li>
			<li class='field clear checkbox'>
				<input type='checkbox' id='leave_link' class='input_check' name='leave' value='y' />
				<label for='leave_link'>{$this->lang->words['leave_link']}</label>
			</li>
		</ul>
	</fieldset>
	<fieldset class='submit'>
		<input type=\"submit\" class='input_submit' value=\"{$this->lang->words['submit_move']}\" /> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$topic['tid']}", "public",'' ), "{$topic['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
	</fieldset>
</div>
</form>";
return $IPBHTML;
}

/* -- moveTopicsForm --*/
function moveTopicsForm($forum, $jump_html, $topics) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_mod', $this->_funcHooks['moveTopicsForm'] ) )
{
$count_7d270a224f8f7d25d1ec60d28ee694fd = is_array($this->functionData['moveTopicsForm']) ? count($this->functionData['moveTopicsForm']) : 0;
$this->functionData['moveTopicsForm'][$count_7d270a224f8f7d25d1ec60d28ee694fd]['forum'] = $forum;
$this->functionData['moveTopicsForm'][$count_7d270a224f8f7d25d1ec60d28ee694fd]['jump_html'] = $jump_html;
$this->functionData['moveTopicsForm'][$count_7d270a224f8f7d25d1ec60d28ee694fd]['topics'] = $topics;
}
$IPBHTML .= "<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=moderate&amp;section=moderate", "public",'' ), "", "" ) . "' method='post'>
<input type='hidden' name='auth_key' value='{$this->member->form_hash}' />
<input type='hidden' name='do' value='topicchoice' />
<input type='hidden' name='tact' value='domove' />
<input type='hidden' name='f' value='{$forum['id']}' />
<input type='hidden' name='st' value='{$this->request['st']}' />
<input type='hidden' name='fromSearch' value='{$this->request['fromSearch']}' />
<input type='hidden' name='returnUrl' value='{$this->request['returnUrl']}' />
<p class='message'>{$this->lang->words['move_exp']}</p>
<br />
<h2 class='maintitle'>{$this->lang->words['cp_tmove_start']}</h2>
<div class='generic_bar'></div>
<div class='post_form' id='mod_form'>
	<fieldset class='row1'>
		<h3 class='bar'>{$this->lang->words['topics_to_move']}</h3>
		<ul>
			" . ((count($topics) AND is_array($topics)) ? ("
				".$this->__f__747a1c57eb5648a0aad372dba66bcff6($forum,$jump_html,$topics)."			") : ("")) . "
		</ul>
	</fieldset>
	<fieldset class='row1'>
		<h3 class='bar'>{$this->lang->words['move_topic_options']}</h3>
		<ul>
			<li class='field'>
				<label for='move_from'>{$this->lang->words['move_from']} <strong>{$forum['name']}</strong> {$this->lang->words['to']}</label>
				<select name=\"df\" id='move_from' class='input_select'>{$jump_html}</select>
			</li>
			<li class='field clear checkbox'>
				<input type='checkbox' id='leave_link' class='input_check' name='leave' value='y' />
				<label for='leave_link'>{$this->lang->words['leave_link']}</label>
			</li>
		</ul>
	</fieldset>
	<fieldset class='submit'>
		<input type=\"submit\" class='input_submit' value=\"{$this->lang->words['submit_move']}\" /> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum['id']}", "public",'' ), "{$forum['name_seo']}", "showforum" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
	</fieldset>
</div>
</form>";
return $IPBHTML;
}


function __f__747a1c57eb5648a0aad372dba66bcff6($forum, $jump_html, $topics)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $topics as $row )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					<li class='field checkbox'>
						<input class='input_check' type=\"checkbox\" name=\"selectedtids[{$row['tid']}]\" id='t_{$row['tid']}' value=\"{$row['tid']}\" checked=\"checked\" />
						<label for='t_{$row['tid']}'>{$row['title']}</label>
					</li>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- pruneSplash --*/
function pruneSplash($forum="", $forums_html="", $confirm_data="", $complete_html="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_mod', $this->_funcHooks['pruneSplash'] ) )
{
$count_4ef6bf4d208be0a0cc268945baf6ea0a = is_array($this->functionData['pruneSplash']) ? count($this->functionData['pruneSplash']) : 0;
$this->functionData['pruneSplash'][$count_4ef6bf4d208be0a0cc268945baf6ea0a]['forum'] = $forum;
$this->functionData['pruneSplash'][$count_4ef6bf4d208be0a0cc268945baf6ea0a]['forums_html'] = $forums_html;
$this->functionData['pruneSplash'][$count_4ef6bf4d208be0a0cc268945baf6ea0a]['confirm_data'] = $confirm_data;
$this->functionData['pruneSplash'][$count_4ef6bf4d208be0a0cc268945baf6ea0a]['complete_html'] = $complete_html;
}
$IPBHTML .= "" . (($complete_html != '') ? ("
	<div class='message'>{$complete_html}</div><br />
") : ("")) . "
	
<h2 class='maintitle'>{$this->lang->words['cp_prune']} {$forum['name']}</h2>
<div class='generic_bar'></div>
<div class='post_form'>
	" . (($confirm_data['show'] == 1) ? ("
		<fieldset>
			<h3 class='bar'>{$this->lang->words['mpt_confirm']}: {$this->lang->words['cp_check_result']}</h3>
			
			<ul>
				<li class='field'>
					<label>{$this->lang->words['cp_total_topics']}</label>
					{$confirm_data['tcount']}
				</li>
				<li class='field'>
					<label>{$this->lang->words['cp_total_match']}</label>
					{$confirm_data['count']}
				</li>
			</ul>
		</fieldset>
	
		<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "{$confirm_data['link']}", "public",'' ), "", "" ) . "' method=\"post\">
		<input type=\"hidden\" name=\"auth_key\" value=\"{$this->member->form_hash}\" />
		<fieldset class='submit'>
			<input type=\"submit\" class='input_submit' value=\"{$confirm_data['link_text']}\" />
		</fieldset>
		</form>
		
	") : ("")) . "
	<form id='postingform' action=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "", "public",'' ), "", "" ) . "\" method=\"post\">
	<input type=\"hidden\" name=\"app\" value=\"forums\" />
	<input type=\"hidden\" name=\"module\" value=\"moderate\" />
	<input type=\"hidden\" name=\"section\" value=\"moderate\" />
	<input type=\"hidden\" name=\"do\" value=\"prune_start\" />
	<input type=\"hidden\" name=\"f\" value=\"{$forum['id']}\" />
	<input type=\"hidden\" name=\"auth_key\" value=\"{$this->member->form_hash}\" />
	<input type=\"hidden\" name=\"check\" value=\"1\" />
	<fieldset>
		<h3 class='bar'>{$this->lang->words['mpt_help']}</h3>
		<p class='ipsPad'>{$this->lang->words['cp_prune_text']}</p><br />
		<ul>
			<li class='field'>
				<label for='df'>{$this->lang->words['cp_prune_action2']}</label>
				<select class='input_select' name=\"df\" id=\"df\">
					<option value='prune'>{$this->lang->words['cp_ac_prune']}</option>
					{$forums_html}
				</select>
			</li>
			<li class='field'>
				<label for='pergo'>{$this->lang->words['cp_per_go']}</label>
				<input class='input_text' type=\"text\" size=\"5\" name=\"pergo\" id=\"pergo\" value=\"{$this->request['pergo']}\" />
			</li>
			<li class='field'>
				<label for='entered_name'>{$this->lang->words['cp_prune_member']}</label>
				<input class='input_text' type=\"text\" size=\"30\" name=\"member\" id='entered_name' value=\"{$this->request['member']}\" />
			</li>
			<li class='field'>
				<label for='dateline'>{$this->lang->words['cp_prune_days2']}</label>
				<input class='input_text' type=\"text\" size=\"5\" name=\"dateline\" id=\"dateline\" value=\"{$this->request['dateline']}\" />
			</li>
			<li class='field'>
				<label for='posts'>{$this->lang->words['cp_prune_replies']}</label>
				<input class='input_text' type=\"text\" size=\"5\" name=\"posts\" id=\"posts\" value=\"{$this->request['posts']}\" />
			</li>
			<li class='field'>
				<label for='topic_type'>{$this->lang->words['cp_prune_type']}</label>
				<select class='input_select' name='topic_type' id=\"topic_type\">
					".$this->__f__043bcfbc08ce3904a009c39a2104885e($forum,$forums_html,$confirm_data,$complete_html)."				</select>
			</li>
			<li class='field'>
				<label for='cbox'>{$this->lang->words['mps_ignorepin']}</label>
				<input class='input_check' type=\"checkbox\" id=\"cbox\" name=\"ignore_pin\" value=\"1\" checked=\"checked\" />
			</li>
			<li class='field'>
				<span class='desc'>{$this->lang->words['cp_optional']}</span>
			</li>
		</ul>
	</fieldset>
	<fieldset class='submit'>
		<input type=\"submit\" class='input_submit' value=\"{$this->lang->words['cp_prune_sub1']}\" /> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum['id']}", "public",'' ), "{$forum['name_seo']}", "showforum" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
	</fieldset>
	</form>
</div>";
return $IPBHTML;
}


function __f__043bcfbc08ce3904a009c39a2104885e($forum="", $forums_html="", $confirm_data="", $complete_html="")
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( array( 'open', 'closed', 'link', 'all' ) as $type )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<option value='{$type}'" . (($this->request['topic_type'] == $type) ? (" selected='selected'") : ("")) . ">{$this->lang->words[ 'cp_pday_' . $type ]}</option>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- simplePage --*/
function simplePage($title="", $msg="") {
$IPBHTML = "";
$IPBHTML .= "<strong>{$title}</strong><br /> {$msg}";
return $IPBHTML;
}

/* -- softDeleteSplash --*/
function softDeleteSplash($forum, $tids=array(), $canHardDelete=false) {
$IPBHTML = "";
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("moderate", "0" ) . "
<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=moderate&amp;section=moderate", "public",'' ), "", "" ) . "' id='mmForm' method='post'>
<input type='hidden' name='auth_key' value='{$this->member->form_hash}' />
<input type='hidden' name='do' value='topicchoice' />
<input type='hidden' name='fromSearch' value='{$this->request['fromSearch']}' />
<input type='hidden' name='returnUrl' value='{$this->request['returnUrl']}' />
<input type='hidden' name='return' value='{$this->request['return']}' />".$this->__f__b81aa4fdab7ecd5ea82db16d936f23d1($forum,$tids,$canHardDelete)."<input type='hidden' name='tact' id='mmTact' value='sdelete' />
<input type='hidden' name='f' value='{$forum['id']}' />
<input type='hidden' name='st' value='{$this->request['st']}' />
<h2 class='maintitle'>" . sprintf($this->lang->words['mm_delete_top'], count( $tids ) ) . "</h2>
<div class='ipsBox clearfix'>
	<div class='ipsBox_container'>
		<div class='ipsPad'>
			{$this->lang->words['dltt_remove_from_view_desc']}<br /><br />
			<input type='text' class='input_text' name='deleteReason' id='delPop_reason' value='' style='width: 60%'  /> <input type='submit' class='input_submit' value='{$this->lang->words['topic_hide']}' />
		</div>
	</div>
</div>
</form>
<script type='text/javascript'>
$('delPop_reason').defaultize( \"{$this->lang->words['topic_hide_reason_default']}\" );
</script>";
return $IPBHTML;
}


function __f__b81aa4fdab7ecd5ea82db16d936f23d1($forum, $tids=array(), $canHardDelete=false)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $tids as $t )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<input type='hidden' name=\"selectedtids[$t]\" value=\"$t\" />

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- softDeleteSplashPosts --*/
function softDeleteSplashPosts($forum, $topic, $pids=array(), $canHardDelete=false) {
$IPBHTML = "";
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("moderate", "0" ) . "
<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=moderate&amp;section=moderate", "public",'' ), "", "" ) . "' id='mmForm' method='post'>
<input type='hidden' name='auth_key' value='{$this->member->form_hash}' />
<input type='hidden' name='do' value='postchoice' />
<input type='hidden' name='fromSearch' value='{$this->request['fromSearch']}' />
<input type='hidden' name='returnUrl' value='{$this->request['returnUrl']}' />
<input type='hidden' name='return' value='{$this->request['return']}' />".$this->__f__2ba38489ffeb5647bb38d7d921550b38($forum,$topic,$pids,$canHardDelete)."<input type='hidden' name='tact' id='mmTact' value='sdelete' />
<input type='hidden' name='f' value='{$forum['id']}' />
<input type='hidden' name='t' value='{$topic['tid']}' />
<input type='hidden' name='st' value='{$this->request['st']}' />
<h2 class='maintitle'>" . sprintf($this->lang->words['mm_delete_top_posts'], count( $pids ) ) . "</h2>
<div class='ipsBox clearfix'>
	<div class='ipsBox_container'>
		<div class='ipsPad ipsForm_center'>
			{$this->lang->words['dlp_remove_from_view_desc']}<br />
			<span class='desc lighter ipsType_smaller'>{$this->lang->words['dlp_remove_from_view_extra']}</span><br /><br />
			<input type='text' class='input_text' name='deleteReason' id='delPop_reason' value='' style='width: 60%'  /> <input type='submit' class='input_submit' value='{$this->lang->words['post_hide']}' />
		</div>
	</div>
</div>
</form>
<script type='text/javascript'>
$('delPop_reason').defaultize( \"{$this->lang->words['post_hide_reason_default']}\" );
</script>";
return $IPBHTML;
}


function __f__2ba38489ffeb5647bb38d7d921550b38($forum, $topic, $pids=array(), $canHardDelete=false)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $pids as $p )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<input type='hidden' name=\"selectedpids[$p]\" value=\"$p\" />

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- splitPostForm --*/
function splitPostForm($forum, $topic, $posts, $jump) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_mod', $this->_funcHooks['splitPostForm'] ) )
{
$count_3a2986e47eee10e20621f03deecd45a4 = is_array($this->functionData['splitPostForm']) ? count($this->functionData['splitPostForm']) : 0;
$this->functionData['splitPostForm'][$count_3a2986e47eee10e20621f03deecd45a4]['forum'] = $forum;
$this->functionData['splitPostForm'][$count_3a2986e47eee10e20621f03deecd45a4]['topic'] = $topic;
$this->functionData['splitPostForm'][$count_3a2986e47eee10e20621f03deecd45a4]['posts'] = $posts;
$this->functionData['splitPostForm'][$count_3a2986e47eee10e20621f03deecd45a4]['jump'] = $jump;
}

$selectedPids	= implode( ',', $this->request['selectedpids'] );
$IPBHTML .= "" . $this->registry->getClass('output')->addJSModule("moderate", "0" ) . "
<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=moderate&amp;section=moderate", "public",'' ), "", "" ) . "' method='post'>
<input type='hidden' name='auth_key' value='{$this->member->form_hash}' />
<input type='hidden' name='do' value='postchoice' />
<input type='hidden' name='t' value='{$topic['tid']}' />
<input type='hidden' name='f' value='{$forum['id']}' />
<input type='hidden' name='tact' value='split' />
<input type='hidden' name='checked' value='1' />
<input type='hidden' name='st' value='{$this->request['st']}' />
<p class='message'>{$this->lang->words['st_explain']}</p>
<br />
<h2 class='maintitle'>{$this->lang->words['st_top']}: {$forum['name']} &gt; {$topic['title']}</h2>
<div class='ipsBox clearfix'>
	<div class='ipsBox_container'>
		<ul>
			<li class='field'>
				<label for='new_title'>{$this->lang->words['mt_new_title']}</label>
				<input type=\"text\" size=\"40\" class='input_text' id='new_title' maxlength=\"100\" name=\"title\" value=\"\" />
			</li>
			<li class='field'>
				<label for='new_forum'>{$this->lang->words['st_forum']}</label>
				<select name=\"fid\" id='new_forum' class='input_select'>{$jump}</select>
			</li>
		</ul>
	</div>
</div>
<br />
<h2 class='maintitle'>{$this->lang->words['st_post']}</h2>
<div class='ipsBox clearfix'>
	<div class='ipsBox_container'>
	" . ((is_array( $posts ) AND count( $posts )) ? ("
		".$this->__f__cc28ca1e46a5315e2785abd8e72584c4($forum,$topic,$posts,$jump)."	") : ("")) . "
	</div>
</div>
<fieldset class='submit'>
		<input type=\"submit\" name=\"submit\" class='input_submit' value=\"{$this->lang->words['st_submit']}\" /> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$topic['tid']}&amp;selectedpids={$selectedPids}", "public",'' ), "{$topic['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
</fieldset>
</form>";
return $IPBHTML;
}


function __f__cc28ca1e46a5315e2785abd8e72584c4($forum, $topic, $posts, $jump)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $posts as $row )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<div class='post_block no_sidebar topic_summary'>
				<h3><input type='checkbox' id='checkbox_{$row['pid']}' name='selectedpids[{$row['pid']}]' value='{$row['pid']}' class='post_mod' checked='checked' /><label for='checkbox_{$row['pid']}' class='post_mod hide'>{$this->lang->words['st_split']}</label> {$row['author_name']}</h3>
				<div class='post_body'>
					<p class='posted_info'>{$this->lang->words['move_posted']} {$row['date']}</p>
					<div class='post'>{$row['post']}</div>
				</div>
			</div>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- topicHistory --*/
function topicHistory($topic, $avg_post, $mod_logs=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_mod', $this->_funcHooks['topicHistory'] ) )
{
$count_86565ab4b10b23989e303b7174d10253 = is_array($this->functionData['topicHistory']) ? count($this->functionData['topicHistory']) : 0;
$this->functionData['topicHistory'][$count_86565ab4b10b23989e303b7174d10253]['topic'] = $topic;
$this->functionData['topicHistory'][$count_86565ab4b10b23989e303b7174d10253]['avg_post'] = $avg_post;
$this->functionData['topicHistory'][$count_86565ab4b10b23989e303b7174d10253]['mod_logs'] = $mod_logs;
}

if ( ! isset( $this->registry->templateStriping['topicHistory'] ) ) {
$this->registry->templateStriping['topicHistory'] = array( FALSE, "row1","row2");
}

if ( ! isset( $this->registry->templateStriping['modlogs'] ) ) {
$this->registry->templateStriping['modlogs'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "<h1 class='ipsType_pagetitle'>{$this->lang->words['th_title']}</h1>
<br />
<div class='ipsBox'>
	<table class='ipb_table' summary=\"{$this->lang->words['topic_history_summary']} '{$topic['title']}'\">
		<tr class='" .  IPSLib::next( $this->registry->templateStriping["topicHistory"] ) . "'>
			<td class='altrow'>{$this->lang->words['th_topic']}</td>
			<td>{$topic['title']}</td>
		</tr>
		<tr class='" .  IPSLib::next( $this->registry->templateStriping["topicHistory"] ) . "'>
			<td class='altrow'>{$this->lang->words['th_start_date']}</td>
			<td>" . $this->registry->getClass('class_localization')->getDate($topic['start_date'],"long", 0) . "</td>
		</tr>
		<tr class='" .  IPSLib::next( $this->registry->templateStriping["topicHistory"] ) . "'>
			<td class='altrow'>{$this->lang->words['th_start_name']}</td>
			<td>" . IPSMember::makeProfileLink( $topic['starter_name'], $topic['starter_id'], $topic['seo_first_name'] ) . "</td>
		</tr>
		<tr class='" .  IPSLib::next( $this->registry->templateStriping["topicHistory"] ) . "'>
			<td class='altrow'>{$this->lang->words['th_last_date']}</td>
			<td>" . $this->registry->getClass('class_localization')->getDate($topic['last_post'],"long", 0) . "</td>
		</tr>
		<tr class='" .  IPSLib::next( $this->registry->templateStriping["topicHistory"] ) . "'>
			<td class='altrow'>{$this->lang->words['th_last_name']}</td>
			<td>" . IPSMember::makeProfileLink( $topic['last_poster_name'], $topic['last_poster_id'], $topic['seo_last_name'] ) . "</td>
		</tr>
		<tr class='" .  IPSLib::next( $this->registry->templateStriping["topicHistory"] ) . "'>
			<td class='altrow'>{$this->lang->words['th_avg_post']}</td>
			<td>{$avg_post}</td>
		</tr>
	</table>
</div>
<br /><br />
<h3 class='maintitle'>{$this->lang->words['ml_title']}</h3>
<table class='ipb_table' summary=\"{$this->lang->words['mod_logs_topic_summary']} '{$topic['title']}'\">
	<tr class='header'>
		<th scope='col' style='width: 25%'>{$this->lang->words['ml_name']}</th>
		<th scope='col' style='width: 50%'>{$this->lang->words['ml_desc']}</th>
		<th scope='col' style='width: 25%'>{$this->lang->words['ml_date']}</th>
	</tr>
	" . ((!count($mod_logs) OR !is_array($mod_logs)) ? ("
		<tr>
			<td class=\"no_messages\" colspan=\"3\">{$this->lang->words['ml_none']}</td>
		</tr>
	") : ("
				".$this->__f__662abc69fd007160cd0ec9489e888bc1($topic,$avg_post,$mod_logs)."	")) . "
</table>";
return $IPBHTML;
}


function __f__662abc69fd007160cd0ec9489e888bc1($topic, $avg_post, $mod_logs=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $mod_logs as $data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<tr class='" .  IPSLib::next( $this->registry->templateStriping["modlogs"] ) . "'>
				<td class='altrow'>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($data) : '' ) . "</td>
				<td>{$data['action']}</td>
				<td class=\"altrow\">" . $this->registry->getClass('class_localization')->getDate($data['ctime'],"long", 0) . "</td>
			</tr>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- unsubscribeForm --*/
function unsubscribeForm($forum, $topic, $text) {
$IPBHTML = "";
$IPBHTML .= "<form action='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=moderate&amp;section=moderate", "public",'' ), "", "" ) . "' method='post'>
<input type='hidden' name='auth_key' value='{$this->member->form_hash}' />
<input type='hidden' name='do' value='31' />
<input type='hidden' name='t' value='{$topic['tid']}' />
<input type='hidden' name='f' value='{$forum['id']}' />
<input type='hidden' name='st' value='{$this->request['st']}' />
<h1 class='ipsType_pagetitle'>{$this->lang->words['ts_title']}: {$forum['name']} &gt; {$topic['title']}</h1>
<br />
<p class='message'>{$text}</p>
<br />
<fieldset class='submit'>
	<input type=\"submit\" class='input_submit' value=\"{$this->lang->words['ts_submit']}\" /> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$topic['tid']}", "public",'' ), "{$topic['title_seo']}", "showtopic" ) . "' title='{$this->lang->words['cancel']}' class='cancel'>{$this->lang->words['cancel']}</a>
</fieldset>
</form>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>