<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 20 Jun 2012 21:29:32 +0000 by Julio César Barrera
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'footer' => "
Regards,

The <#BOARD_NAME#> team.
<#BOARD_ADDRESS#>
 ",
'header' => "",
'new_comment_on_entry' => "Hello!

This email has been sent from: <#BOARD_NAME#>.

A new comment has been made on <#BLOG_NAME#>.

----------------------------------
Entry: <#ENTRY_NAME#>
Author: <#POSTER#>
Comment:
<#COMMENT#>
----------------------------------

The comment can be found here:
<#URL#>
",
'noblog_youcan_postto' => "You don't have any blogs that can be posted into. Please create one and try again",
'send_entry_text' => "I thought you might be interested in reading this Blog page: <#THE LINK#>

From,

<#USER NAME#>
",
'subject__new_comment_on_entry' => "New Comment on",
'subject__subs_new_entry' => "Blog Tracker New Entry Notification",
'subs_new_entry' => "<#NAME#>,

<#POSTER#> has just posted a new entry entitled \"<#ENTRY_NAME#>\" in blog \"<#BLOG_NAME#>\".

----------------------------------------------------------------------
<#ENTRY#>
----------------------------------------------------------------------

The entry can be found here:
<#BOARD_ADDRESS#>?app=blog&module=display&section=blog&blogid=<#BLOG_ID#>&showentry=<#ENTRY_ID#>

Unsubscribing:
--------------

You can unsubscribe at any time by logging into your control panel and clicking on the \"Blog Tracker\" link in the \"Blog\" tab.
",
 ); 
