<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 20 Jun 2012 21:29:32 +0000 by Julio César Barrera
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'menu__blog_akismet' => "Akismet Logs",
'menu__blog_cblocks' => "Content Blocks",
'menu__blog_dheaders' => "Dynamic Headers Set-Up",
'menu__blog_manage' => "Blog Manager",
'menu__blog_managech' => "Manage Custom Headers",
'menu__blog_mem_themes' => "Manage Member Themes",
'menu__blog_overview' => "Overview",
'menu__blog_rebuild' => "Rebuild",
'menu__blog_settings' => "Settings",
'menu__blog_themes' => "Manage Custom Themes",
'menu__blog_trackbacks' => "Trackback &amp; Ping Services",
'r__blogs_akismet' => "Blog Akismet Logs",
'r__blogs_akismet_delete' => "Can delete Akismet logs?",
'r__blogs_akismet_spamham' => "Can submit spam and ham to Akismet?",
'r__blogs_akismet_view' => "Can view Akismet logs?",
'r__blogs_cblocks' => "Blog Content Block Management",
'r__blogs_cdelete' => "Can delete content blocks?",
'r__blogs_cheaders' => "Blog Custom Header Management",
'r__blogs_cmanage' => "Can add/edit content blocks?",
'r__blogs_delete' => "Can delete blogs?",
'r__blogs_dheaders' => "Blog Dynamic Headers Management",
'r__blogs_manage' => "Can edit blogs?",
'r__blogs_managet' => "Blog Management",
'r__blogs_pings' => "Blog Pings Management",
'r__blogs_themes' => "Blog Theme Management",
'r__blogs_tools' => "Blog Tools",
'r__blog_attach' => "Can fix old attachments?",
'r__blog_dheader' => "Can manage dynamic headers?",
'r__blog_furls' => "Can check and fix friendly urls?",
'r__blog_header_delete' => "Can delete custom headers?",
'r__blog_header_manage' => "Can add/edit custom headers?",
'r__blog_ping_manage' => "Can add/edit ping services?",
'r__blog_ping_remove' => "Can remove ping services?",
'r__blog_stats' => "Can rebuild stats?",
'r__blog_tb_manage' => "Can restore and remove trackbacks?",
'r__blog_tb_view' => "Can view trackback logs?",
'r__blog_theme_approve' => "Can approve custom themes?",
'r__blog_theme_delete' => "Can delete themes?",
'r__blog_theme_manage' => "Can add/edit themes?",
'r__blog_thumbs' => "Can rebuild entry thumbnails?",
'r__blog_tool_resync' => "Can resynchronize blogs and entries?",
 ); 
