<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 20 Jun 2012 21:29:32 +0000 by Julio César Barrera
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'approve_link' => "Approve",
'approve_x_comments' => "Approve",
'check_all' => "Check all",
'click here to login' => "click here to log in",
'comments_act_go' => "Go",
'comments_header' => "Comments",
'comment_action_count' => "With <span id='comment_count'>#{count}</span> checked comments:",
'comment_approval_required' => "Your comment requires moderator approval before it will be shown.",
'comment_button_post' => "Add Comment",
'comment_hidden_content' => "Toggle Content",
'comment_notice_subject' => "A new comment has been left on <a href='%s'>%s</a>",
'comment_notifications' => "<#NAME#>,

<#AUTHOR#> has just commented on \"<#TITLE#>\", here: <#URL#>.

<div class='callout'><#COMMENT#></div>

You can review the new comment here:
<#COMMENTURL#>",
'comment_permalink' => "Get the permalink",
'comment_reply' => "Quote",
'comment_save' => "Save",
'comm_confirm_delete' => "Confirm Delete",
'comm_confirm_delete_desc' => "Are you sure you want to delete this comment?",
'comm_confirm_hide' => "Hide Comment",
'comm_confirm_hide_desc' => "This option hides the comment, but moderators may still be able to view it.",
'delete_comment' => "Delete comment",
'delete_link' => "Delete",
'delete_x_comments' => "Delete",
'del_comm_now' => "Delete comment now",
'edit_comment' => "Editing comment from:",
'edit_link' => "Edit",
'hide_link' => "Hide",
'hide_x_comments' => "Hide",
'ignored_comments_not' => "This comment is hidden because you have chosen to ignore posts by",
'manage_comments_pop' => "Manage Comments",
'mobile_add_comment' => "Add Comment",
'mq_image_add' => "MultiQuote",
'no_reason_given' => "No Reason Given",
'permalink' => "Permalink:",
'post_deleted_by' => "Comment Hidden By",
'reply_to_comment' => "Reply directly to this comment",
'report_link' => "Report",
'sign_in' => "Sign In",
'unapprove_x_comments' => "Un-approve",
'unhide_link' => "Unhide",
'unhide_x_comments' => "Unhide",
'view_comment' => "View comment",
'view_it_anyway' => "View it anyway?",
'yourname_captcha' => "Your Name:",
 ); 
