<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 20 Jun 2012 21:29:32 +0000 by Julio César Barrera
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'fave_title' => "%s",
'freq_daily' => "Daily",
'freq_immediate' => "Instantly",
'freq_offline' => "Only when not online",
'freq_weekly' => "Weekly",
'label_anon' => "Follow Anonymously",
'label_anon_desc' => "Do not show me in the summary",
'label_freq' => "Frequency",
'label_notify' => "Receive notification",
'likeadded' => "Added:",
'likedby' => "Followed By",
'pg_no_longer_following' => "You are no longer following this item",
'pg_unfollow_confirm' => "Unfollow This Item Now",
'pg_unfollow_text' => "<strong>%s</strong>, you have elected to unfollow the item <a href='%s'>%s</a>.<br />If you unfollow, you will no longer receive notifcations when this item is updated.",
'pg_unfollow_title' => "Unfollow Item",
'pg_unlike_done' => "Item unfollowed successfully",
 ); 
