<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 20 Jun 2012 21:29:32 +0000 by Julio César Barrera
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'simple_tag_add' => "Add tags",
'simple_tag_add_button' => "Add",
'simple_tag_add_explanation' => "Separate multiple tags by comma",
'simple_tag_delete' => "Delete tags",
'simple_tag_delete_button' => "Delete",
'simple_tag_edit' => "Edit tags",
 ); 
