<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 20 Jun 2012 21:29:32 +0000 by Julio César Barrera
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'mem_change_button' => "Change...",
'mem_posts' => "Posts",
'mem_remove_avatar' => "Remove Avatar",
'm_overrride' => "Override group permission masks with...",
 ); 
