<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 20 Jun 2012 21:29:32 +0000 by Julio César Barrera
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'forum_leaders' => "The moderating team",
'goto_profile' => "Go to profile",
'go_button' => "Go",
'leader_admins' => "Administrators",
'leader_all_forums' => "All Forums",
'leader_forums' => "Forums",
'leader_global' => "Global Moderators",
'leader_group' => "Group",
'leader_last_seen' => "Last Active",
'leader_location' => "Location",
'leader_mods' => "Forum Moderators",
'leader_name' => "Member Name",
'member' => "Member",
'member_joined' => "Joined",
'member_percent' => "% of today's posts",
'member_posts' => "Total Member Posts",
'member_today' => "Posts Today",
'm_online' => "Online",
'notopic_attach' => "Could not load attachments for the requested topic",
'no_forums' => "View %s Forums",
'no_info' => "No information is available at this time",
'stats_missing_tid' => "You must select a valid topic for this feature",
'todays_posters' => "Today's Top 20 Posters",
'topic_noattach' => "The specified topic does not have any attachments",
'topic_noperms' => "You do not have permission to access this forum",
'top_poster_title' => "Today's top 20 posters",
'whoposted_name' => "Member name",
'whoposted_posts' => "Posts",
'who_farted' => "Who posted in:",
'who_replied_title' => "Who posted in this topic",
 ); 
