<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 20 Jun 2012 21:29:32 +0000 by Julio César Barrera
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'cannot_del_img' => "Could not delete the linkback image. Please login via FTP to remove the image",
'cannot_del_root' => "You can not delete the last root category",
'cannot_move_there' => "You can not move the subcategories to a category within the one you are deleting",
'delete_bad_cat_id' => "Unable to delete the category because an invalid category ID was specified",
'edit_bad_cat_id' => "Unable to edit the category because an invalid category ID was specified",
'empty_bad_cat_id' => "Unable to empty the category because an invalid category ID was specified",
'img_bad_extension' => "The file you selected is not an acceptable image. Please try again with an image having a valid extension: %s",
'links_dir_unwritable' => "The links directory within your uploads folder isn't writable and an attempt to make it writable failed. Please ensure the directory is writable (CHMOD 777)",
'no_cat_title' => "Unable to proceed because you did not specify a category title",
'no_img_selected' => "You did not select a file to upload",
'no_linkback_img' => "You did not select a file to upload as a new linkback image",
'no_links_dir' => "We could not find the links directory within your uploads folder and an attempt to create it failed. Please make sure there is a 'links' folder within your uploads directly and that it is writable (CHMOD 777)",
'resync_bad_cat_id' => "Unable to resynchronize the category because an invalid category ID was specified",
'uploads_not_writable' => "Your uploads directory does not appear to be writable. Double check your upload path at System -> System Settings -> General Configuration",
'upload_img_err' => "The image could not be uploaded. Please ensure that your uploads directory is writable (CHMOD 777)",
 ); 
