<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 20 Jun 2012 21:29:32 +0000 by Julio César Barrera
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'actions' => "Actions",
'active_users_header' => "user(s) active in the past %s minutes",
'add_to_favorites' => "Add to Favorites",
'advanced_stats' => "Advanced Statistics",
'all_comments' => "View All Comments",
'anon_members' => "anonymous member(s)",
'categories' => "Categories",
'click_to_show_opts' => "Click to configure posting options",
'comments' => "Comments",
'debug_error' => "Cannot initialize rating object, no polling URL supplied",
'delete_article_confirm' => "Are you sure you want to delete this tutorial?  There will be no further confirmation screens.",
'delete_comment_confirm' => "Are you sure you want to delete this comment?  There will be no further confirmation screens.",
'favorites_list' => "My Favorite Tutorials",
'got_post_errors' => "The following error was returned by classPost.php",
'guests' => "guest(s)",
'new_tutorial' => "Submit New Tutorial",
'no_edit_topic' => "Topic could not be edited",
'no_post_reply' => "Topic reply could not be posted",
'no_post_topic' => "Topic could not be posted",
'no_view_tutorials' => "You do not have permission to view the Tutorials System.",
'offline_title' => " (OFFLINE)",
'pending_tutorials' => "Pending Tutorials",
'random_article' => "Random Tutorial",
'ratings' => "Ratings",
'rating_failed' => "There was an error saving your rating for this Tutorial.",
'remove_from_favorites' => "Remove from Favorites",
'topic_edit_failed' => "Topic editing failed",
'topic_post_failed' => "Topic posting failed",
'topic_reply_failed' => "Topic reply failed",
'tutorials' => "Tutorials",
'tutorials_not_online' => "The Tutorials system is offline at this time.",
'tutorials_stats' => "Tutorials System Statistics",
'views' => "Views",
 ); 
