<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 20 Jun 2012 21:29:32 +0000 by Julio César Barrera
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'groups_td_accept' => "Can accept user submitted tutorials?",
'groups_td_add' => "Can submit new tutorials?",
'groups_td_attach_max' => "Total upload size for attachments (in KB)?",
'groups_td_attach_max_blurb' => "Enter -1 to disable uploads or enter 0 to disable the limit.",
'groups_td_attach_per_post' => "Maximum upload size for attachments per article (in KB)?",
'groups_td_attach_per_post_blurb' => "Enter 0 to disable a per post limit. This number must be less than the total amount.",
'groups_td_comadd' => "Can submit new comments?",
'groups_td_comdelete' => "Can delete their own comments?",
'groups_td_comedit' => "Can edit their own comments?",
'groups_td_comview' => "Can view comments?",
'groups_td_copy' => "Can copy existing tutorials to a new category?",
'groups_td_delete' => "Can delete their own tutorials?",
'groups_td_download' => "Can download tutorials?",
'groups_td_edit' => "Can edit their own tutorials?",
'groups_td_mod_comdelete' => "Can delete other members&#39; comments?",
'groups_td_mod_comedit' => "Can edit other members&#39; comments?",
'groups_td_mod_delete' => "Can delete other members&#39; tutorials?",
'groups_td_mod_edit' => "Can edit other members&#39; tutorials?",
'groups_td_othermems' => "Can create tutorials as other members?",
'groups_td_posthtml' => "Can post HTML in their tutorials?",
'groups_td_print' => "Can print tutorials?",
'groups_td_rate' => "Can rate tutorials?",
'groups_td_starthidden' => "Can specify new tutorials they create are hidden?",
'groups_td_view' => "Can view the Tutorials system?",
'groups_td_view_offline' => "Can access the Tutorials system in OFFLINE mode?",
'groups_td_view_random' => "Can view Random tutorials?",
'groups_td_view_stats' => "Can view the Advanced Stats page?",
'grps_attach' => "Attachment Permissions",
'grps_comment' => "Comment Options",
'grps_create' => "Tutorial Creation",
'grps_global' => "Global Options",
'grps_moderate' => "Moderator Permissions",
'grps_viewing' => "Tutorial Viewing",
'mod_title' => "(IM) Tutorials",
 ); 
