<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Wed, 20 Jun 2012 21:29:32 +0000 by Julio César Barrera
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'approved_article' => "Approved article",
'approved_selected' => "Approved the selected articles",
'approved_the_article' => "Approved the article '%s'",
'article_already_approved' => "That article is already approved, silly.",
'article_already_unapproved' => "That article is already hidden, silly.",
'category' => "Category",
'comsystem_offline' => "The commenting system is currently offline.",
'confirm_rejection' => "Confirm Rejection",
'created_by' => "Created By",
'deleted_article' => "Deleted article",
'deleted_comment' => "Deleted comment #%s",
'deleted_the_article' => "Deleted the article",
'deleted_the_comment' => "Deleted the comment",
'dopm_approved_subject' => "Your tutorial submission was approved&#33;",
'dopm_approved_text' => "This is an automatically generated message.

Your recent tutorial submission (%s) was approved. If you have any questions, please feel free to reply to the staff member who approved your submission.

Thanks!",
'dopm_rejected_subject' => "Your tutorial submission was denied.",
'dopm_rejected_text' => "This is an automatically generated message.

Your recent tutorial submission ({article_name}) was denied. {reason}If you have any questions, please feel free to reply to the staff member who denied your submission.

Thanks!",
'incorrect_action' => "You have chosen an incorrect action.  Stop messing about.",
'moderate_art_no_id' => "You must be logged in to perform any tutorial moderation functions.",
'moderate_bulk_no_id' => "You must be logged in to perform any tutorial bulk moderation functions.",
'moderate_com_no_id' => "You must be logged in to perform any comment moderation functions. ",
'no_approve_permissions' => "You do not have permission to approve articles.",
'no_article_to_delete' => "Sorry, we could not find the article you were attempting to delete.",
'no_article_to_toggle' => "We could not find the article you were attempting to hide/show.",
'no_comment_articles' => "You do not have commenting permissions in this category.",
'no_delete_permissions' => "You do not have permission to delete that.",
'no_ids_passed' => "No IDs were passed to perform multi-moderation on.",
'no_reject_permissions' => "You do not have permission to reject articles.",
'no_view_permissions' => "You do not have permission to read tutorials in this category.",
'pending_table_summary' => "Articles pending staff approval",
'pending_tutorials' => "Pending Tutorials",
'rejected_article' => "Rejected article",
'rejected_selected' => "Rejected the selected articles",
'rejection_form' => "Rejection Form",
'rejection_reason' => "Rejection Reason",
'reject_reason' => "The following reason was given for this rejection:",
'tutorial' => "Tutorial",
'unapproved_article' => "Unapproved article",
'unapproved_the_article' => "Unapproved the article '%s'",
 ); 
