<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sun, 24 Jun 2012 00:32:25 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'fave_title' => "Set as favorite",
'freq_daily' => "Daily",
'freq_immediate' => "Instantly",
'freq_offline' => "Only when not online",
'freq_weekly' => "Weekly",
'label_anon' => "Set Favorite Anonymously",
'label_anon_desc' => "Do not show me in favorites list",
'label_freq' => "Frequency",
'label_notify' => "Receive notification of %s",
 ); 
