<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sun, 24 Jun 2012 00:32:25 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'mi_cant_import' => "Cannot import",
'mi_current_title' => "Current Mobile App Images",
'mi_error_cannot_write' => "The directory %s is not writeable",
'mi_error_doesnt_exist' => "The directory %s doesn't exist",
'mi_error_images_writeable' => "Some images aren't writeable, see below for details",
'mi_error_missing_img' => "The image %s is missing!",
'mi_error_no_export' => "The export failed",
'mi_error_refresh_failed' => "Refresh Failed",
'mi_exportxml' => "Export as XMLArchive",
'mi_img_not_dims' => "Incorrect size, should be %s",
'mi_img_not_writable' => "Not writeable",
'mi_import_failed' => "The import failed",
'mi_import_title' => "Import Images XMLArchive",
'mi_information' => "If you wish to change these images, you can either use the <strong>Import Images XMLArchive</strong> button to import an existing XML Archive or you can upload the images individually to the <strong>%s</strong> directory on your server. If you do choose to manually upload the images, please click the <strong>recache</strong> button when complete.",
'mi_recache' => "Recache",
'mi_recache_done' => "Recache complete",
'mi_select_xml' => "Select XMLArchive",
'mi_title' => "Mobile App iOS Images",
'mi_tt_filename' => "Filename",
'mi_tt_modified' => "Modified",
'mi_tt_size' => "Size",
'mi_upload' => "Upload",
 ); 
