<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sun, 24 Jun 2012 00:32:25 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'article_no_exist' => "That tutorial doesn't exist!",
'attached_file' => "Attached File",
'attach_hits' => "Number of downloads",
'attach_missing_id' => "We could not determine which tutorial you were attempting to view attachments from.",
'attach_no_attachments' => "The specified tutorial does not have any attachments to view.",
'attach_no_cat_perm' => "You do not have permission to view attachments in the category this tutorial is in.",
'attach_page_title' => "Attachments",
'attach_post_date' => "Posted on",
'attach_size' => "Size:",
'attach_title' => "Attachment",
'error_no_results' => "Sorry, no tutorials matched your search criteria",
'no_download_perm' => "You do not have permission to download tutorials.",
'no_print_perm' => "You do not have permission to print tutorials.",
'no_random' => "You have no permission to view any tutorials, apparently.",
'no_read_articles' => "You do not have permission to read tutorials in this category.",
'posted' => "Posted",
'random_not_allowed' => "You do not have permission to view Random Tutorials.",
 ); 
