<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Wed, 29 Aug 2012 14:14:59 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_boards_2 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['birthday'] = array('age');
$this->_funcHooks['boardIndexTemplate'] = array('unreadicon','hideDateUrl','forumRedirect','forums','cat_has_forums','categories','cats_forums');
$this->_funcHooks['hookRecentBlogEntries'] = array('entries_hook','recent_blog_entries');
$this->_funcHooks['hookRecentTopics'] = array('topics_hook','recenttopics');
$this->_funcHooks['hookWatchedItems'] = array('watched_forums','watched_hook_old','watched_hook','watched_hook_old','updatedforumsn','updatedforums','noupdatedforums','updatedtopicsn','updatedtopics','noupdatedtopics');


}

/* -- birthday --*/
function birthday($user, $pyear) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['birthday'] ) )
{
$count_a5381a4a7078aa63fd34c9edae888279 = is_array($this->functionData['birthday']) ? count($this->functionData['birthday']) : 0;
$this->functionData['birthday'][$count_a5381a4a7078aa63fd34c9edae888279]['user'] = $user;
$this->functionData['birthday'][$count_a5381a4a7078aa63fd34c9edae888279]['pyear'] = $pyear;
}
$IPBHTML .= "<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$user['member_id']}", "public",'' ), "{$user['members_seo_name']}", "showuser" ) . "' title='{$this->lang->words['view_profile']}'>{$user['members_display_name']}</a>" . (($pyear) ? (" (<strong>{$pyear}</strong>)") : ("")) . "";
return $IPBHTML;
}

/* -- boardIndexTemplate --*/
function boardIndexTemplate($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['boardIndexTemplate'] ) )
{
$count_9577d6b80157fa1a6731fe367b6be67d = is_array($this->functionData['boardIndexTemplate']) ? count($this->functionData['boardIndexTemplate']) : 0;
$this->functionData['boardIndexTemplate'][$count_9577d6b80157fa1a6731fe367b6be67d]['lastvisit'] = $lastvisit;
$this->functionData['boardIndexTemplate'][$count_9577d6b80157fa1a6731fe367b6be67d]['stats'] = $stats;
$this->functionData['boardIndexTemplate'][$count_9577d6b80157fa1a6731fe367b6be67d]['cat_data'] = $cat_data;
$this->functionData['boardIndexTemplate'][$count_9577d6b80157fa1a6731fe367b6be67d]['show_side_blocks'] = $show_side_blocks;
$this->functionData['boardIndexTemplate'][$count_9577d6b80157fa1a6731fe367b6be67d]['side_blocks'] = $side_blocks;
}
$IPBHTML .= "" . (($this->settings['_onIndex'] = 1) ? ("") : ("")) . "
<div class='master_list' id='board_index'>
	" . ((is_array( $cat_data ) AND count( $cat_data )) ? ("
		".$this->__f__e913d2f40dbb4992054d8e114ee4085a($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks)."	") : ("")) . "
</div>";
return $IPBHTML;
}


function __f__8700d1576e015d635191f40cd3752200($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array(),$_data='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $_data['forum_data'] as $forum_id => $forum_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
					" . (($forum_data['redirect_on']) ? ("
						<div class='row touch-row' id=\"forum-{$forum_data['id']}\">
							<div class='icon'>" . $this->registry->getClass('output')->getReplacement("f_redirect") . "</div>
							<div class='rowContent'>
								<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='{$forum_data['name']}' class='title'>{$forum_data['name']}</a>
								<br /><span class='desc'>{$this->lang->words['rd_hits']}: " . $this->registry->getClass('class_localization')->formatNumber( $forum_data['redirect_hits'] ) . "</span>
							</div>
						</div>
					") : ("<div class='row touch-row' id=\"forum-{$forum_data['id']}\">
							<div class='icon'>
								" . (($forum_data['img_new_post'] != 'f_locked' && strstr( $forum_data['img_new_post'], 'unread' )) ? ("
									<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=forums&amp;module=forums&amp;section=markasread&amp;marktype=forum&amp;forumid={$forum_data['id']}&amp;returntoforumid={$this->request['f']}&amp;i=1", "public",'' ), "", "" ) . "\" title=\"{$this->lang->words['bi_markread']}\" class='forum_marker'>
										" . $this->registry->getClass('output')->getReplacement("f_unread") . "
									</a>
								") : ("
									" . $this->registry->getClass('output')->getReplacement("f_read") . "
								")) . "
							</div>
							<div class='rowContent'>
								<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$forum_data['id']}", "public",'' ), "{$forum_data['name_seo']}", "showforum" ) . "\" title='{$forum_data['name']}' class='title'>{$forum_data['name']}</a>
								<br />
								<span class='desc'>
									<span class='number'>{$forum_data['topics']}</span> {$this->lang->words['topics']}
									" . ((! $forum_data['hide_last_info']) ? ("
										&middot; {$this->lang->words['last_post']} " . $this->registry->getClass('class_localization')->getDate($forum_data['last_post'],"SHORT", 0) . "
									") : ("")) . "
								</span>
							</div>
						</div>")) . "
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__e913d2f40dbb4992054d8e114ee4085a($lastvisit="", $stats=array(), $cat_data=array(), $show_side_blocks=true, $side_blocks=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $cat_data as $_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			" . ((is_array( $_data['forum_data'] ) AND count( $_data['forum_data'] )) ? ("
				<h3 id=\"cat-{$_data['cat_data']['id']}\">{$_data['cat_data']['name']}</h3>
				".$this->__f__8700d1576e015d635191f40cd3752200($lastvisit,$stats,$cat_data,$show_side_blocks,$side_blocks,$_data)."			") : ("")) . "
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hookBoardIndexShareLinks --*/
function hookBoardIndexShareLinks($data) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- hookBoardIndexStatusUpdates --*/
function hookBoardIndexStatusUpdates($updates=array()) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- hookFacebookActivity --*/
function hookFacebookActivity() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- hookRecentBlogEntries --*/
function hookRecentBlogEntries($entries) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookRecentBlogEntries'] ) )
{
$count_56510a732092497b72649030eedf8079 = is_array($this->functionData['hookRecentBlogEntries']) ? count($this->functionData['hookRecentBlogEntries']) : 0;
$this->functionData['hookRecentBlogEntries'][$count_56510a732092497b72649030eedf8079]['entries'] = $entries;
}

if ( ! isset( $this->registry->templateStriping['recent_entries'] ) ) {
$this->registry->templateStriping['recent_entries'] = array( FALSE, "row1","row2 altrow");
}
$IPBHTML .= "<div class='general_box clearfix'>
		<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='' /> {$this->lang->words['recently_added_entries']}</h3>
		<ul class='hfeed block_list'>
			" . ((is_array( $entries ) && count( $entries )) ? ("
								".$this->__f__689ad027b655fdf807d592ccae72f171($entries)."			") : ("
				<li>{$this->lang->words['norecent_entries_hook']}</li>
			")) . "
		</ul>
	</div>";
return $IPBHTML;
}


function __f__689ad027b655fdf807d592ccae72f171($entries)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $entries as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<li class='hentry " .  IPSLib::next( $this->registry->templateStriping["recent_entries"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$r['blog_id']}&amp;showentry={$r['entry_id']}", "public",'' ), "{$r['entry_name_seo']}", "showentry" ) . "' rel='bookmark' title='{$this->lang->words['view_entry']}'>{$r['entry_name']}</a> {$this->lang->words['recent_by']} <address class=\"author vcard\"><a class=\"url fn\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['entry_author_id']}", "public",'' ), "{$r['members_seo_name']}", "showuser" ) . "\" title='{$this->lang->words['view_profile']}'>{$r['members_display_name']}</a></address><br /><span class='date'><abbr class=\"published\" title=\"" . date( 'c', $r['entry_date'] ) . "\">" . $this->registry->getClass('class_localization')->getDate($r['entry_date'],"short", 0) . "</abbr></span></li>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hookRecentTopics --*/
function hookRecentTopics($topics) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookRecentTopics'] ) )
{
$count_d8bc74bc173013416894b0c01d8bae74 = is_array($this->functionData['hookRecentTopics']) ? count($this->functionData['hookRecentTopics']) : 0;
$this->functionData['hookRecentTopics'][$count_d8bc74bc173013416894b0c01d8bae74]['topics'] = $topics;
}

if ( ! isset( $this->registry->templateStriping['recent_topics'] ) ) {
$this->registry->templateStriping['recent_topics'] = array( FALSE, "row1","row2 altrow");
}
$IPBHTML .= "<div class='general_box clearfix'>
		<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='' /> {$this->lang->words['recently_added_topics']}</h3>
		<ul class='hfeed block_list'>
			" . ((is_array( $topics ) && count( $topics )) ? ("
								".$this->__f__9982fc4aac2f19aaadf1c760a73f4fb7($topics)."			") : ("
				<li>{$this->lang->words['norecent_topics_hook']}</li>
			")) . "
		</ul>
	</div>";
return $IPBHTML;
}


function __f__9982fc4aac2f19aaadf1c760a73f4fb7($topics)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $topics as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
				<li class='hentry " .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['tid']}", "public",'' ), "{$r['title_seo']}", "showtopic" ) . "' rel='bookmark' title='{$this->lang->words['view_topic']}'>{$r['title']}</a> 
				{$this->lang->words['recent_by']} <address class=\"author vcard\">" . (($r['members_display_name']) ? ("<a class=\"url fn\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['starter_id']}", "public",'' ), "{$r['members_seo_name']}", "showuser" ) . "\" title='{$this->lang->words['view_profile']}'>{$r['members_display_name']}</a>") : ("{$this->settings['guest_name_pre']}{$r['starter_name']}{$this->settings['guest_name_suf']}")) . "</address><br />
				<span class='date'><abbr class=\"published\" title=\"" . date( 'c', $r['start_date'] ) . "\">" . $this->registry->getClass('class_localization')->getDate($r['start_date'],"short", 0) . "</abbr></span></li>
				
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- hookTagCloud --*/
function hookTagCloud($tags) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- hookWatchedItems --*/
function hookWatchedItems($updatedTopics, $nUpdatedTopics, $updatedForums, $nUpdatedForums) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_boards', $this->_funcHooks['hookWatchedItems'] ) )
{
$count_21dd2e209e0bcaddb49b0de7dad346ed = is_array($this->functionData['hookWatchedItems']) ? count($this->functionData['hookWatchedItems']) : 0;
$this->functionData['hookWatchedItems'][$count_21dd2e209e0bcaddb49b0de7dad346ed]['updatedTopics'] = $updatedTopics;
$this->functionData['hookWatchedItems'][$count_21dd2e209e0bcaddb49b0de7dad346ed]['nUpdatedTopics'] = $nUpdatedTopics;
$this->functionData['hookWatchedItems'][$count_21dd2e209e0bcaddb49b0de7dad346ed]['updatedForums'] = $updatedForums;
$this->functionData['hookWatchedItems'][$count_21dd2e209e0bcaddb49b0de7dad346ed]['nUpdatedForums'] = $nUpdatedForums;
}

if ( ! isset( $this->registry->templateStriping['recent_topics'] ) ) {
$this->registry->templateStriping['recent_topics'] = array( FALSE, "row1","row2 altrow");
}

if ( ! isset( $this->registry->templateStriping['recent_topics'] ) ) {
$this->registry->templateStriping['recent_topics'] = array( FALSE, "row1","row2 altrow");
}
$IPBHTML .= "<div class='general_box alt clearfix' id='hook_watched_items'>
		<h3><img src='{$this->settings['img_url']}/comment_new.png' alt='' /> {$this->lang->words['wi_content_title']}</h3>
		<div class='recent_activity'>
			<ol class='tab_bar no_title mini'>
				<li id='tab_link_forums' class='tab_toggle active clickable'>{$this->lang->words['watched_forums']}</li>
				<li id='tab_link_topics' class='tab_toggle clickable'>{$this->lang->words['watched_topics']}</li>
			</ol>
			<div id='tab_content_forums' class='tab_toggle_content'>
				" . ((is_array( $updatedForums ) && count( $updatedForums )) ? ("
					<ul class='clearfix'>
												".$this->__f__e717972a26f080c6d3a5fc492e2c733d($updatedTopics,$nUpdatedTopics,$updatedForums,$nUpdatedForums)."					</ul>
				") : ("<ul class='clearfix'>
						" . ((!is_array( $nUpdatedForums ) OR !count( $nUpdatedForums )) ? ("
							<li class='" .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'>{$this->lang->words['wi_not_watch']}</li>
						") : ("")) . "
					</ul>")) . "
				" . ((is_array( $nUpdatedForums ) && count( $nUpdatedForums )) ? ("
					<div id='more-watched-forums-container' style='display:none;'>
						<ul>
							".$this->__f__cb97480e12f95fc2676a307526824ad2($updatedTopics,$nUpdatedTopics,$updatedForums,$nUpdatedForums)."						</ul>
					</div>
					<fieldset class='submit'>
						<input type='button' class='input_submit alt clickable' id='more-watched-forums' value='{$this->lang->words['wi_toggle_start']} {$this->lang->words['wi_toggle_end']}' />
					</fieldset>
				") : ("")) . "
			</div>
			
			<div id='tab_content_topics' class='tab_toggle_content' style='display:none;'>
								" . ((is_array( $updatedTopics ) && count( $updatedTopics )) ? ("
					<ul class='hfeed'>
						".$this->__f__e9bcf2cc73df132c52a6f9fb35d37073($updatedTopics,$nUpdatedTopics,$updatedForums,$nUpdatedForums)."					</ul>
				") : ("" . ((!is_array( $nUpdatedTopics ) OR !count( $nUpdatedTopics )) ? ("
						<ul class='hfeed'>
							<li class='" .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'>{$this->lang->words['wi_no_topics']}</li>
						</ul>
					") : ("")) . "")) . "
				" . ((is_array( $nUpdatedTopics ) && count( $nUpdatedTopics )) ? ("
					<div id='more-watched-topics-container' style='display:none;'>
						<ul class='hfeed'>
							".$this->__f__f0106e35e8d510d65d83ef0528e6bf94($updatedTopics,$nUpdatedTopics,$updatedForums,$nUpdatedForums)."						</ul>
					</div>
					<fieldset class='submit'>
						<input type='button' id='more-watched-topics' class='input_submit alt clickable' value='{$this->lang->words['wi_toggle_start']} {$this->lang->words['wi_t_toggle_end']}' />
					</fieldset>
				") : ("")) . "
			</div>
		</div>
	</div>";
return $IPBHTML;
}


function __f__e717972a26f080c6d3a5fc492e2c733d($updatedTopics, $nUpdatedTopics, $updatedForums, $nUpdatedForums)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $updatedForums as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							<li class='" .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$r['id']}", "public",'' ), "{$r['name_seo']}", "showforum" ) . "' rel='bookmark' title='{$this->lang->words['view_forum']}'>{$r['name']}</a></li>
						
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__cb97480e12f95fc2676a307526824ad2($updatedTopics, $nUpdatedTopics, $updatedForums, $nUpdatedForums)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $nUpdatedForums as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
								<li class='" .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showforum={$r['id']}", "public",'' ), "{$r['name_seo']}", "showforum" ) . "' rel='bookmark' title='{$this->lang->words['view_forum']}'>{$r['name']}</a><br />
									<span class='desc'>{$this->lang->words['wi_no_new']}</span>
								</li>
							
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__e9bcf2cc73df132c52a6f9fb35d37073($updatedTopics, $nUpdatedTopics, $updatedForums, $nUpdatedForums)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $updatedTopics as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							<li class='hentry " .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['tid']}&amp;view=getnewpost", "public",'' ), "{$r['title_seo']}", "showtopic" ) . "' rel='bookmark' title='{$this->lang->words['view_topic']}'>{$r['title']}</a> {$this->lang->words['recent_by']} <address class=\"author vcard\"><a class=\"url fn\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['last_poster_id']}", "public",'' ), "{$r['members_seo_name']}", "showuser" ) . "\" title='{$this->lang->words['view_profile']}'>{$r['last_poster_name']}</a></address><br /><span class='date'><abbr class=\"published\" title=\"" . date( 'c', $r['last_post'] ) . "\">" . $this->registry->getClass('class_localization')->getDate($r['last_post'],"short", 0) . "</abbr></span></li>
						
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__f0106e35e8d510d65d83ef0528e6bf94($updatedTopics, $nUpdatedTopics, $updatedForums, $nUpdatedForums)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $nUpdatedTopics as $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
								<li class='hentry " .  IPSLib::next( $this->registry->templateStriping["recent_topics"] ) . "'><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$r['tid']}&amp;view=getnewpost", "public",'' ), "{$r['title_seo']}", "showtopic" ) . "' rel='bookmark' title='{$this->lang->words['view_topic']}'>{$r['title']}</a> {$this->lang->words['recent_by']} <address class=\"author vcard\"><a class=\"url fn\" href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$r['last_poster_id']}", "public",'' ), "{$r['members_seo_name']}", "showuser" ) . "\" title='{$this->lang->words['view_profile']}'>{$r['last_poster_name']}</a></address><br /><span class='date'><abbr class=\"published\" title=\"" . date( 'c', $r['last_post'] ) . "\">" . $this->registry->getClass('class_localization')->getDate($r['last_post'],"short", 0) . "</abbr></span></li>
							
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- statusReplies --*/
function statusReplies($replies=array()) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- statusUpdates --*/
function statusUpdates($updates=array(), $smallSpace=0, $latestOnly=0) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>