<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Wed, 29 Aug 2012 14:14:59 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_global_comments_2 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['commentsList'] = array('comments','comments_top','allow_comments','comments_bottom');
$this->_funcHooks['form'] = array('comment_errors','guest_captcha');


}

/* -- comment --*/
function comment($r, $parent, $settings) {
$IPBHTML = "";

// Adjust author name as needed
if( empty($r['author']['member_id']) && !empty($r['author']['comment_author_name']) )
{
	$r['author']['members_display_name'] = $r['author']['comment_author_name'];
}
$IPBHTML .= "<a id='comment_{$r['comment']['comment_id']}'></a>
<div class=\"row\" id=\"comment-{$r['comment']['comment_id']}\">
	<div class='icon'>
		<img src='{$r['author']['pp_thumb_photo']}' width='{$r['author']['pp_thumb_width']}' height='{$r['author']['pp_thumb_height']}' class='photo' />
	</div>
	<div class='rowContent'>
		<h4>" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($r['author']) : '' ) . ", <span class='desc'>" . $this->registry->getClass('class_localization')->getDate($r['comment']['comment_date'],"short", 0) . "</span></h4>
		{$r['comment']['comment_text']}
	</div>
</div>";
return $IPBHTML;
}

/* -- commentHidden --*/
function commentHidden($r, $parent, $settings) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- commentsList --*/
function commentsList($comments, $settings, $pages, $parent, $preReply='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['commentsList'] ) )
{
$count_0bdd271f4e9be8f6262d38fc21703907 = is_array($this->functionData['commentsList']) ? count($this->functionData['commentsList']) : 0;
$this->functionData['commentsList'][$count_0bdd271f4e9be8f6262d38fc21703907]['comments'] = $comments;
$this->functionData['commentsList'][$count_0bdd271f4e9be8f6262d38fc21703907]['settings'] = $settings;
$this->functionData['commentsList'][$count_0bdd271f4e9be8f6262d38fc21703907]['pages'] = $pages;
$this->functionData['commentsList'][$count_0bdd271f4e9be8f6262d38fc21703907]['parent'] = $parent;
$this->functionData['commentsList'][$count_0bdd271f4e9be8f6262d38fc21703907]['preReply'] = $preReply;
}
$IPBHTML .= "<a id='commentsStart'></a>
" . (($pages) ? ("
	<div class='topic_controls'>
		{$pages}
	</div>
") : ("")) . "
<h3>{$this->lang->words['comments_header']}</h3>
<div class='comment_wrap' id='comment_wrap'>
	".$this->__f__959cacf3cddb8a33043feff455e7d5c0($comments,$settings,$pages,$parent,$preReply)."</div>
" . (($parent['_canComment']) ? ("
<h2>{$this->lang->words['mobile_add_comment']}</h2>
	<a id=\"fastreply\"></a>
	<div id='fast_reply'>
		<div>
			<form action=\"{$settings['formUrl']}\" method=\"post\">
				<input type=\"hidden\" name=\"auth_key\" value=\"{$this->member->form_hash}\" />
				<input type=\"hidden\" name=\"fromApp\" value=\"{$settings['fromApp']}\" />
				<input type=\"hidden\" name=\"app\" value=\"{$settings['formApp']}\" />
				<input type=\"hidden\" name=\"module\" value=\"{$settings['formModule']}\" />
				<input type=\"hidden\" name=\"section\" value=\"{$settings['formSection']}\" />
				<input type=\"hidden\" name=\"do\" value=\"add\" />
				<input type=\"hidden\" name=\"parentId\" value=\"{$parent['parent_id']}\" />
				<input type=\"hidden\" name=\"fast_reply_used\" value=\"1\" />
				<div id='commentReply'>
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('editors'), 'editorShell' ) ? $this->registry->getClass('output')->getTemplate('editors')->editorShell('fast-reply', 'Post', $preReply, 1, 1) : '' ) . "
				</div>
				<div id='commentButtons'>
				<input type='submit' name=\"submit\" class='input_submit' id='commentPost' value='{$this->lang->words['comment_button_post']}' tabindex='2' accesskey='s' />
				</div>
			</form>
		</div>
	</div>
") : ("")) . "
" . (($pages) ? ("
	<div class='topic_controls'>
		{$pages}
	</div>
") : ("")) . "";
return $IPBHTML;
}


function __f__959cacf3cddb8a33043feff455e7d5c0($comments, $settings, $pages, $parent, $preReply='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $comments as $id => $r )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		" . ( method_exists( $this->registry->getClass('output')->getTemplate('global_comments'), 'comment' ) ? $this->registry->getClass('output')->getTemplate('global_comments')->comment($r, $parent, $settings) : '' ) . "
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- form --*/
function form($comment, $parent, $editor="", $settings, $errors="", $do='saveEdit') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['form'] ) )
{
$count_0c7f7a2c3001f74a142a949cc7612c21 = is_array($this->functionData['form']) ? count($this->functionData['form']) : 0;
$this->functionData['form'][$count_0c7f7a2c3001f74a142a949cc7612c21]['comment'] = $comment;
$this->functionData['form'][$count_0c7f7a2c3001f74a142a949cc7612c21]['parent'] = $parent;
$this->functionData['form'][$count_0c7f7a2c3001f74a142a949cc7612c21]['editor'] = $editor;
$this->functionData['form'][$count_0c7f7a2c3001f74a142a949cc7612c21]['settings'] = $settings;
$this->functionData['form'][$count_0c7f7a2c3001f74a142a949cc7612c21]['errors'] = $errors;
$this->functionData['form'][$count_0c7f7a2c3001f74a142a949cc7612c21]['do'] = $do;
}
$IPBHTML .= "" . (($errors) ? ("
	<p class='message error'>{$errors}</p>
") : ("")) . "
<div class='post_form'>
	<form method=\"post\" action=\"{$this->settings['base_url']}\" name=\"REPLIER\">
		<input type=\"hidden\" name=\"auth_key\" value=\"{$this->member->form_hash}\" />
		<input type=\"hidden\" name=\"fromApp\" value=\"{$settings['fromApp']}\" />
		<input type=\"hidden\" name=\"app\" value=\"core\" />
		<input type=\"hidden\" name=\"module\" value=\"global\" />
		<input type=\"hidden\" name=\"section\" value=\"comments\" />	
		<input type=\"hidden\" name=\"do\" value=\"saveEdit\" />
		<input type=\"hidden\" name=\"parentId\" value=\"{$parent['parent_id']}\" />
		<input type=\"hidden\" name=\"comment_id\" value=\"{$comment['comment']['comment_id']}\" />
		<input type=\"hidden\" name=\"auth_key\" value=\"{$this->member->form_hash}\" />
		
		<h3 class='maintitle'>
		" . (($do == 'saveEdit') ? ("
			{$this->lang->words['edit_comment']} {$parent['parent_title']}
		") : ("")) . "
		</h3>
		<div class='generic_bar'></div>
		
		" . ((!$this->memberData['member_id'] AND $this->settings['guest_captcha'] AND $this->settings['bot_antispam_type'] != 'none') ? ("
			<fieldset>
				<ul>
					<li class='field'>
						<label for=''>{$this->lang->words['guest_captcha']}</label>
						{$imgid}
					</li>
				</ul>
			</fieldset>
		") : ("")) . "
		
		<fieldset>
			{$editor}
		</fieldset>
		<fieldset class='submit'>
			<input type=\"submit\" name=\"submit\" value=\"{$this->lang->words['comment_save']}\" tabindex=\"0\" class=\"input_submit\" accesskey=\"s\" /> {$this->lang->words['or']} <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=global&amp;section=comments&amp;do=findComment&amp;comment_id={$comment['comment']['comment_id']}&amp;parentId={$parent['parent_id']}&amp;fromApp={$settings['fromApp']}", "public",'' ), "", "" ) . "' class='cancel' title='{$this->lang->words['cancel']}'>{$this->lang->words['cancel']}</a>
		</fieldset>
	</form>
</div>";
return $IPBHTML;
}

/* -- getEditJs --*/
function getEditJs() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>