<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Wed, 29 Aug 2012 14:14:59 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_blog_cblocks_2 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['cblock_footer'] = array('inlineeditcustomcblock','exteditcustomcblock','isCustomBlock');
$this->_funcHooks['cblock_friends'] = array('recentLoop','anyfriends');
$this->_funcHooks['cblock_header'] = array('thisismyblog');
$this->_funcHooks['last_comment_row'] = array('newcomment');
$this->_funcHooks['latest_visitors'] = array('recentLoop','anyvisitors');
$this->_funcHooks['mini_cal_mini_wrap'] = array('minicalday');
$this->_funcHooks['recentEntries'] = array('newcomment');


}

/* -- album_row --*/
function album_row($album="") {
$IPBHTML = "";
$IPBHTML .= "<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;album={$album['album_id']}", "public",'' ), "{$album['album_name_seo']}", "viewalbum" ) . "\">{$album['album_name']}</a><br />";
return $IPBHTML;
}

/* -- block_activeusers --*/
function block_activeusers($active="") {
$IPBHTML = "";
$IPBHTML .= "<strong>{$active['GUESTS']}</strong> {$this->lang->words['guests']}<br />
	<strong>{$active['MEMBERS']}</strong> {$this->lang->words['public_members']}<br />
	<strong>{$active['ANON']}</strong> {$this->lang->words['anon_members']}<br /><br />
	{$active['NAMES']}";
return $IPBHTML;
}

/* -- blog_cblocks --*/
function blog_cblocks($content, $position, $hidden) {
$IPBHTML = "";
$IPBHTML .= "<div id='cblock_{$position}' class='cblock'>
	{$content}
</div>";
return $IPBHTML;
}

/* -- categories --*/
function categories($blogid, $categories=array()) {
$IPBHTML = "";
$IPBHTML .= "" . ((count( $categories ) > 7) ? ("
<ul class='largeblock_rows categories'>
") : ("
<ul class='block_rows categories'>
")) . "" . ((is_array( $categories ) AND count( $categories )) ? ("".$this->__f__3d72b90c7fd5b7b074915c21e3d2e82b($blogid,$categories)."	") : ("")) . "
</ul>";
return $IPBHTML;
}


function __f__3d72b90c7fd5b7b074915c21e3d2e82b($blogid, $categories=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $categories as $cid => $cdata )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li>" . $this->registry->getClass('output')->getReplacement("blog_category") . " &nbsp; <a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;blogid={$blogid}&amp;cat={$cid}", "public",'' ), "{$cdata['category_title_seo']}", "blogcatview" ) . "'>{$cdata['category_title']} (" . intval($cdata['count']) . ")</a></li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- cblock_footer --*/
function cblock_footer($cblock="",$auth_key="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_cblocks', $this->_funcHooks['cblock_footer'] ) )
{
$count_5a8f6329dbeb3b167850f09696deee89 = is_array($this->functionData['cblock_footer']) ? count($this->functionData['cblock_footer']) : 0;
$this->functionData['cblock_footer'][$count_5a8f6329dbeb3b167850f09696deee89]['cblock'] = $cblock;
$this->functionData['cblock_footer'][$count_5a8f6329dbeb3b167850f09696deee89]['auth_key'] = $auth_key;
}
$IPBHTML .= "</div>
	" . (($cblock['cblock_type']=='custom') ? ("" . (($this->settings['blog_inline_edit']) ? ("
			<br />
			<ul class='right'>
				<li class='ipsButton_secondary'>
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=post&amp;section=post&amp;do=editcblock&amp;blogid={$cblock['blog_id']}&amp;cbid={$cblock['cbcus_id']}&amp;inline=1", "public",'' ), "", "" ) . "\">{$this->lang->words['block_edit']}</a>
				</li>
				<li class='ipsButton_secondary important'>
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&module=post&section=mod&do=delcblock&blogid={$cblock['blog_id']}&cbid={$cblock['cblock_id']}&auth_key={$auth_key}", "public",'' ), "", "" ) . "\" class='delete_block'>{$this->lang->words['block_delete']}</a>
				</li>
			</ul>
			<br class='clear' />
		") : ("")) . "
		" . (($cblock['allow_edit'] && !$this->settings['blog_inline_edit']) ? ("
			<br />
			<ul class='right'>
				<li class='ipsButton_secondary'>
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=post&amp;section=post&amp;do=editcblock&amp;blogid={$cblock['blog_id']}&amp;cbid={$cblock['cbcus_id']}&amp;inline=1", "public",'' ), "", "" ) . "\">{$this->lang->words['block_edit']}</a>
				</li>
				<li class='ipsButton_secondary important'>
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&module=post&section=mod&do=delcblock&blogid={$cblock['blog_id']}&cbid={$cblock['cblock_id']}&auth_key={$auth_key}", "public",'' ), "", "" ) . "\" class='delete_block'>{$this->lang->words['block_delete']}</a>
				</li>
			</ul>
			<br class='clear' />
		") : ("")) . "") : ("")) . "
</div>";
return $IPBHTML;
}

/* -- cblock_friends --*/
function cblock_friends($friends=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_cblocks', $this->_funcHooks['cblock_friends'] ) )
{
$count_e14ab6e638edea69f075d4f797c0f413 = is_array($this->functionData['cblock_friends']) ? count($this->functionData['cblock_friends']) : 0;
$this->functionData['cblock_friends'][$count_e14ab6e638edea69f075d4f797c0f413]['friends'] = $friends;
}

if ( ! isset( $this->registry->templateStriping['friendBlogs'] ) ) {
$this->registry->templateStriping['friendBlogs'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "" . ((is_array( $friends ) && count( $friends )) ? ("
	<ul class='ipsList_withminiphoto'>
				".$this->__f__6a39771f01272d98090cea2b15ba448b($friends)."	</ul>
") : ("
	<div class='no_messages'>{$this->lang->words['friends_no_blogs']}</div>
")) . "";
return $IPBHTML;
}


function __f__6a39771f01272d98090cea2b15ba448b($friends=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $friends as $fid => $friend )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li class='" .  IPSLib::next( $this->registry->templateStriping["friendBlogs"] ) . " ipsPad_half clearfix'>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$friend['member_id']}", "public",'' ), "{$friend['members_seo_name']}", "showuser" ) . "' class='ipsUserPhotoLink left ipsPad_half'>
					<img src='{$friend['pp_small_photo']}' alt='{$this->lang->words['photo']}' class='ipsUserPhoto ipsUserPhoto_mini' />
				</a>
				<div class='list_content'>
					<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$friend['blog_id']}", "public",'' ), "{$friend['blog_seo_name']}", "showblog" ) . "' title='{$friend['blog_name']}'><strong>{$friend['blog_name']}</strong></a>
					<div class='desc'>
						{$this->lang->words['by_ucfirst']} " . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($friend) : '' ) . "
					</div>
				</div>
			</li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- cblock_header --*/
function cblock_header($cblock,$title="", $configable=0, $nopad=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_cblocks', $this->_funcHooks['cblock_header'] ) )
{
$count_41b3f840651d4a29196b23251240d598 = is_array($this->functionData['cblock_header']) ? count($this->functionData['cblock_header']) : 0;
$this->functionData['cblock_header'][$count_41b3f840651d4a29196b23251240d598]['cblock'] = $cblock;
$this->functionData['cblock_header'][$count_41b3f840651d4a29196b23251240d598]['title'] = $title;
$this->functionData['cblock_header'][$count_41b3f840651d4a29196b23251240d598]['configable'] = $configable;
$this->functionData['cblock_header'][$count_41b3f840651d4a29196b23251240d598]['nopad'] = $nopad;
}
$IPBHTML .= "<div id='cblock_{$cblock['cblock_id']}' class='general_box cblock_drag alt'>
" . (($this->registry->blogFunctions->blog['member_id'] == $this->memberData['member_id']) ? ("<h3 class='draggable'><span class='cblock_title'>{$title}</span></h3>
	" . (($this->settings['blog_inline_edit'] && $cblock['cblock_id'] > 0) ? ("" . (($configable) ? ("
			<a href='#' class='configure_link'>{$this->lang->words['block_config']}</a>
		") : ("")) . "" . (($this->settings['blog_allow_cblockchange']) ? ("
			<a href='#' class='close_link'><img src='{$this->settings['img_url']}/close_popup.png' alt='x' /></a>
		") : ("")) . "") : ("")) . "") : ("
	<h3><span class='cblock_title'>{$title}</span></h3>
")) . "
<div class='cblock_inner" . (($nopad) ? (" nopad") : ("")) . " row1'>";
return $IPBHTML;
}

/* -- comments --*/
function comments($html) {
$IPBHTML = "";

if ( ! isset( $this->registry->templateStriping['comments'] ) ) {
$this->registry->templateStriping['comments'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "<ul class='block_rows'>
	{$html}
</ul>";
return $IPBHTML;
}

/* -- config_digg --*/
function config_digg($config, $cblock) {
$IPBHTML = "";
$IPBHTML .= "<div class='short'>
	<label for='digg_user'>{$this->lang->words['digg_username']}: <input type=\"text\" id=\"digg_user\" name=\"digg_user\" value=\"{$config['digg_user']}\" class='input_text' /></label><br /><br />
	<input class=\"input_submit\" id='digg_config' type=\"button\" value=\"{$this->lang->words['save_settings_c']}\" />
	<script type='text/javascript'>
		$('digg_config').observe('click', ipb.blog.saveCblock.bindAsEventListener( this, {$cblock['cblock_id']}, [\"digg_user\"] ) );
	</script>
</div>";
return $IPBHTML;
}

/* -- config_google --*/
function config_google($config, $cblock) {
$IPBHTML = "";
$IPBHTML .= "<div class='short'>
	
	<label for='shareditems_id'>{$this->lang->words['google_id']}: <input type=\"text\" id=\"shareditems_id\" name=\"shareditems_id\" value=\"{$config['shareditems_id']}\" /></label><br /><br />
	<input class=\"input_submit\" id='google_config' type=\"button\" value=\"{$this->lang->words['save_settings_c']}\" />
	
	<script type='text/javascript'>
		$('google_config').observe('click', ipb.blog.saveCblock.bindAsEventListener( this, {$cblock['cblock_id']}, [\"shareditems_id\"] ) );
	</script>
		
		
</div>";
return $IPBHTML;
}

/* -- config_mybloglog --*/
function config_mybloglog($config, $cblock) {
$IPBHTML = "";
$IPBHTML .= "<div class='short'>
	<label for='mybloglog_id'>{$this->lang->words['google_id']}: <input type='text' id='mybloglog_id' name='mybloglog_id' value='{$config['mybloglog_id']}' /></label><br /><br />
	<input class='input_submit' id='mybloglog_config' type='button' value='{$this->lang->words['save_settings_c']}' />
	<script type='text/javascript'>
		$('mybloglog_config').observe('click', ipb.blog.saveCblock.bindAsEventListener( this, {$cblock['cblock_id']}, [\"mybloglog_id\"] ) );
	</script>		
</div>";
return $IPBHTML;
}

/* -- config_twitter --*/
function config_twitter($config, $cblock, $friend_sel) {
$IPBHTML = "";
$IPBHTML .= "<div class='short'>
	<strong>{$this->lang->words['account_settings_c']}</strong><br /><br />
		<label for='twitter_username'>{$this->lang->words['lastfm_username']}: <input type=\"text\" id=\"twitter_username\" name=\"twitter_username\" value=\"{$config['twitter_username']}\" class='input_text' /></label><br />
		<label for='twitter_id'>{$this->lang->words['google_id']}: <input type=\"text\" id=\"twitter_id\" name=\"twitter_id\" value=\"{$config['twitter_id']}\" class='input_text' /></label><br /><br />
		
	<strong>{$this->lang->words['lastfm_display']}</strong><br /><br />
		<select name='twitter_friends' id='twitter_friends'>
			<option value='1'{$friend_sel[0]}>{$this->lang->words['twitter_friends1']}</option>
			<option value='0'{$friend_sel[1]}>{$this->lang->words['twitter_friends2']}</option>
		</select>
		<br /><br />
		
	<input class=\"input_submit\" id='twitter_config' type=\"button\" value=\"{$this->lang->words['save_settings_c']}\" />
		
	<script type='text/javascript'>
		$('twitter_config').observe('click', ipb.blog.saveCblock.bindAsEventListener( this, {$cblock['cblock_id']}, [\"twitter_username\", \"twitter_id\", \"twitter_friends\"] ) );
	</script>
		
		
</div>";
return $IPBHTML;
}

/* -- config_visitors --*/
function config_visitors($config, $cblock) {
$IPBHTML = "";
$IPBHTML .= "<div class='short'>
	<label for='num_latest_visitors'>{$this->lang->words['visitor_how_many']}: <input type=\"text\" id=\"num_latest_visitors\" name=\"num_latest_visitors\" value=\"{$config['num_latest_visitors']}\" /></label><br /><br />
	<input class=\"input_submit\" id='visitors_config' type=\"button\" value=\"{$this->lang->words['save_settings_c']}\" />
	
	<script type='text/javascript'>
		$('visitors_config').observe('click', ipb.blog.saveCblock.bindAsEventListener( this, {$cblock['cblock_id']}, [\"num_latest_visitors\"] ) );
	</script>		
</div>";
return $IPBHTML;
}

/* -- get_my_search --*/
function get_my_search($blogid="") {
$IPBHTML = "";
$IPBHTML .= "<form method='post' action='{$this->settings['base_url']}app=core&amp;module=search&amp;do=quick_search&amp;search_filter_app[blog]=1' id='context_search'>
	<input type='hidden' name='type' value='blog' />
	<input type='hidden' name='type_id' value='{$blogid}' />
	<div class='short'>
		<input type=\"text\" style=\"width:90%;\" name=\"search_term\"  onfocus=\"this.value=''\" value=\"{$this->lang->words['blog_enter_search']}\" /><br />
		<input type=\"submit\" class='input_submit' value=\"{$this->lang->words['jmp_go']}\" />
	</div>
</form>";
return $IPBHTML;
}

/* -- last_comment_row --*/
function last_comment_row($comment="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_cblocks', $this->_funcHooks['last_comment_row'] ) )
{
$count_ab46d06676b4c440f9998251a301fa1d = is_array($this->functionData['last_comment_row']) ? count($this->functionData['last_comment_row']) : 0;
$this->functionData['last_comment_row'][$count_ab46d06676b4c440f9998251a301fa1d]['comment'] = $comment;
}

if ( ! isset( $this->registry->templateStriping['recentcomments'] ) ) {
$this->registry->templateStriping['recentcomments'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "<li class='" .  IPSLib::next( $this->registry->templateStriping["recentcomments"] ) . "' style='clear:both'>
	<img src='{$comment['pp_mini_photo']}' width='{$comment['pp_mini_width']}' height='{$comment['pp_mini_height']}' alt='' class='photo' />
	<div class='nexttophoto'>{$comment['memberlink']}
	 <span class='desc'>{$this->lang->words['comment_on']} {$comment['_comment_date']}</span>
	 <br />
	 " . (($comment['newpost']) ? ("
		 <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$this->registry->blogFunctions->blog['blog_id']}&amp;showentry={$comment['entry_id']}&amp;cid={$comment['comment_id']}&amp;show=comment", "public",'' ), "{$comment['entry_name_seo']}", "showentry" ) . "\" title=\"{$this->lang->words['view_comment']}\">" . $this->registry->getClass('output')->getReplacement("f_newpost") . "</a>
	") : ("")) . "<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$this->registry->blogFunctions->blog['blog_id']}&amp;showentry={$comment['entry_id']}&amp;cid={$comment['comment_id']}&amp;show=comment", "public",'' ), "{$comment['entry_name_seo']}", "showentry" ) . "\"><strong>{$comment['entry_name']}</strong></a>
	</div>
</li>";
return $IPBHTML;
}

/* -- latest_visitors --*/
function latest_visitors($visitors=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_cblocks', $this->_funcHooks['latest_visitors'] ) )
{
$count_c4c5c971c7f97740e6c069e5fd8a89af = is_array($this->functionData['latest_visitors']) ? count($this->functionData['latest_visitors']) : 0;
$this->functionData['latest_visitors'][$count_c4c5c971c7f97740e6c069e5fd8a89af]['visitors'] = $visitors;
}

if ( ! isset( $this->registry->templateStriping['visitorRow'] ) ) {
$this->registry->templateStriping['visitorRow'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "" . ((is_array( $visitors ) && count( $visitors )) ? ("
	<ul class='ipsList_withminiphoto'>
				".$this->__f__587a139852223654a9dc28960e2cdfeb($visitors)."	</ul>
") : ("
	<div class='no_messages'>{$this->lang->words['blog_no_visitors']}</div>
")) . "";
return $IPBHTML;
}


function __f__587a139852223654a9dc28960e2cdfeb($visitors=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $visitors as $vid => $visitor )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li class='" .  IPSLib::next( $this->registry->templateStriping["visitorRow"] ) . " ipsPad_half clearfix'>
				<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$visitor['member_id']}", "public",'' ), "{$visitor['members_seo_name']}", "showuser" ) . "' class='ipsUserPhotoLink left ipsPad_half'>
					<img src='{$visitor['pp_small_photo']}' alt='{$this->lang->words['photo']}' class='ipsUserPhoto ipsUserPhoto_mini' />
				</a>
				<div class='list_content ipsPad_half'>
					" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'userHoverCard' ) ? $this->registry->getClass('output')->getTemplate('global')->userHoverCard($visitor) : '' ) . "
					<div class='desc'>
						" . $this->registry->getClass('class_localization')->getDate($visitor['visited_date'],"TINY", 0) . "
					</div>
				</div>
			</li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- mini_cal_blank_cell --*/
function mini_cal_blank_cell() {
$IPBHTML = "";
$IPBHTML .= "<td class=\"row1 altrow\">&nbsp;<!-- no content --></td>";
return $IPBHTML;
}

/* -- mini_cal_date_cell --*/
function mini_cal_date_cell($month_day="") {
$IPBHTML = "";
$IPBHTML .= "<td" . ((strstr($month_day, '<a href')) ? (" class='cellHasEntry'") : ("")) . ">$month_day</td>";
return $IPBHTML;
}

/* -- mini_cal_date_cell_today --*/
function mini_cal_date_cell_today($month_day="") {
$IPBHTML = "";
$IPBHTML .= "<td class=\"today\">
	<strong>$month_day</strong>
</td>";
return $IPBHTML;
}

/* -- mini_cal_day_bit --*/
function mini_cal_day_bit($day="") {
$IPBHTML = "";
$IPBHTML .= "<td width=\"14%\" class=\"subtitle\">$day</td>";
return $IPBHTML;
}

/* -- mini_cal_mini_wrap --*/
function mini_cal_mini_wrap($content="", $days) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_cblocks', $this->_funcHooks['mini_cal_mini_wrap'] ) )
{
$count_ba53dcb1d1dd26d0eb6d6162274ad3ee = is_array($this->functionData['mini_cal_mini_wrap']) ? count($this->functionData['mini_cal_mini_wrap']) : 0;
$this->functionData['mini_cal_mini_wrap'][$count_ba53dcb1d1dd26d0eb6d6162274ad3ee]['content'] = $content;
$this->functionData['mini_cal_mini_wrap'][$count_ba53dcb1d1dd26d0eb6d6162274ad3ee]['days'] = $days;
}
$IPBHTML .= "<table class='mini_cal row1'>
	<tr class='header'>
		".$this->__f__60eb907e7702aba532e96b179afc42f4($content,$days)."	</tr>
	<tr>
			{$content}
	</tr>
</table>";
return $IPBHTML;
}


function __f__60eb907e7702aba532e96b179afc42f4($content="", $days)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $days as $day )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<th class='row1 altrow cwd'>$day</th>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- mini_cal_new_row --*/
function mini_cal_new_row($week="") {
$IPBHTML = "";
$IPBHTML .= "</tr>
	<!-- NEW ROW-->
<tr>";
return $IPBHTML;
}

/* -- recentEntries --*/
function recentEntries($entries="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_blog_cblocks', $this->_funcHooks['recentEntries'] ) )
{
$count_1f73850907cf436230c3c6064a1051b7 = is_array($this->functionData['recentEntries']) ? count($this->functionData['recentEntries']) : 0;
$this->functionData['recentEntries'][$count_1f73850907cf436230c3c6064a1051b7]['entries'] = $entries;
}

if ( ! isset( $this->registry->templateStriping['recententries'] ) ) {
$this->registry->templateStriping['recententries'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "<ul class='block_rows'>
	" . ((is_array( $entries )) ? ("".$this->__f__80ed3f49bf03e2e228228d91861b9f72($entries)."	") : ("")) . "
</ul>";
return $IPBHTML;
}


function __f__80ed3f49bf03e2e228228d91861b9f72($entries="")
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $entries as $eid => $entry )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<li class='" .  IPSLib::next( $this->registry->templateStriping["recententries"] ) . "' style='clear:both'>
				<img src='{$entry['pp_mini_photo']}' width='{$entry['pp_mini_width']}' height='{$entry['pp_mini_height']}' alt='' class='photo' />
				<div class='nexttophoto'>
					" . (($entry['newpost']) ? ("
					 <a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$entry['blog_id']}&amp;showentry={$entry['entry_id']}", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\">" . $this->registry->getClass('output')->getReplacement("f_newpost") . "</a>&nbsp;
					") : ("")) . "
					<a href=\"" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=blog&amp;module=display&amp;section=blog&amp;blogid={$this->registry->blogFunctions->blog['blog_id']}&amp;showentry={$entry['entry_id']}", "public",'' ), "{$entry['entry_name_seo']}", "showentry" ) . "\"><strong>{$entry['entry_name']}</strong></a>
					<p class='desc'>{$this->lang->words['comment_on']} {$entry['_entry_date']}</p>
				</div>
			</li>
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- show_cblock --*/
function show_cblock($cblock="") {
$IPBHTML = "";
$IPBHTML .= "{$cblock['cbcus']} " . (($cblock['cbcus_has_attach']) ? ("<!--IBF.ATTACHMENT_{$cblock['cbcus_id']}-->") : ("")) . "";
return $IPBHTML;
}

/* -- show_mypicture --*/
function show_mypicture($member=array(),$blog=array()) {
$IPBHTML = "";
$IPBHTML .= "<center>
	<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showuser={$member['member_id']}", "public",'' ), "{$member['members_seo_name']}", "showuser" ) . "' class='ipsUserPhotoLink ipsPad_half'>
		<img src='{$member['pp_small_photo']}' alt='{$this->lang->words['photo']}' class='ipsUserPhoto ipsUserPhoto_medium' />
	</a>
</center>";
return $IPBHTML;
}

/* -- show_random_album_image --*/
function show_random_album_image($image_link="") {
$IPBHTML = "";
$IPBHTML .= "<center>{$image_link}</center>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>