<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Wed, 29 Aug 2012 14:14:59 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_home_2 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['home'] = array('globalAlbums');


}

/* -- browse --*/
function browse($children, $album, $pages, $stats) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- home --*/
function home($feature, $sidebars, $albums) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_gallery_home', $this->_funcHooks['home'] ) )
{
$count_50bfbdd376881ddb9f739aed8362f6ff = is_array($this->functionData['home']) ? count($this->functionData['home']) : 0;
$this->functionData['home'][$count_50bfbdd376881ddb9f739aed8362f6ff]['feature'] = $feature;
$this->functionData['home'][$count_50bfbdd376881ddb9f739aed8362f6ff]['sidebars'] = $sidebars;
$this->functionData['home'][$count_50bfbdd376881ddb9f739aed8362f6ff]['albums'] = $albums;
}
$IPBHTML .= "<h2 class=\"gallery_title\">" . IPSLib::getAppTitle('gallery') . "</h2>
<h3>{$this->lang->words['home_recent_images']}</h3>
<div class='row' style=\"text-align: center; margin:6px 0px\">
	".$this->__f__6cf31abc0d2a234db84fb272c51c389d($feature,$sidebars,$albums)."</div>
" . ((is_array($sidebars['globalAlbums'])) ? ("
	" . ( method_exists( $this->registry->getClass('output')->getTemplate('gallery_albums'), 'miniAlbumStripHorizontal' ) ? $this->registry->getClass('output')->getTemplate('gallery_albums')->miniAlbumStripHorizontal($sidebars['globalAlbums'], $this->lang->words['home_active_global_albums']) : '' ) . "
") : ("")) . "
<div class=\"master_list\">
<h3>{$this->lang->words['home_recent_albums']}</h3>".$this->__f__6ad7ab212fcc6e114422a64becf89d6a($feature,$sidebars,$albums)."</div>";
return $IPBHTML;
}


function __f__6cf31abc0d2a234db84fb272c51c389d($feature, $sidebars, $albums)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $sidebars['recentImages'] as $id => $image )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<div style=\"margin:2px 1px; display: inline-block; min-height: 50px; border:1px solid #777;\">
			" . $this->registry->getClass('gallery')->inlineResize( $image['thumb'],'thumb_small','','' ) . "
		</div>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__6ad7ab212fcc6e114422a64becf89d6a($feature, $sidebars, $albums)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $albums as $i => $album )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
	<div class=\"row touch-row\" id=\"album-members-{$album['album_id']}\">
		<div class='icon'>
			" . $this->registry->getClass('gallery')->inlineResize( $album['thumb'],'thumb_small','','' ) . "
		</div>
		<div class='rowContent'>
			<a id=\"album-members-{$album['album_id']}_primaryUrl\"  href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=gallery&amp;album={$album['album_id']}", "public",'' ), "{$album['album_name_seo']}", "viewalbum" ) . "'>{$album['album_name']}</a>
			<br />
			<span class='desc'>
				" . intval($album['album_count_imgs']) . " {$this->lang->words['stats_total_images']}
				" . (($album['idate'] && ! isset( $album['_children_'] )) ? ("
					<br />{$this->lang->words['last_ucfirst']}: " . $this->registry->getClass('class_localization')->getDate($album['idate'],"short", 0) . "
				") : ("")) . "
			</span>
		</div>
	</div>

";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>