<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 2               */
/* CACHE FILE: Generated: Wed, 29 Aug 2012 14:14:59 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_legends_2 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['bbcodePopUpList'] = array('bbcode');
$this->_funcHooks['emoticonPopUpList'] = array('emoticons');


}

/* -- bbcodePopUpList --*/
function bbcodePopUpList($rows) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_legends', $this->_funcHooks['bbcodePopUpList'] ) )
{
$count_9271fe2410e16b9ce14c7f56f1d0a343 = is_array($this->functionData['bbcodePopUpList']) ? count($this->functionData['bbcodePopUpList']) : 0;
$this->functionData['bbcodePopUpList'][$count_9271fe2410e16b9ce14c7f56f1d0a343]['rows'] = $rows;
}
$IPBHTML .= "<h2>{$this->lang->words['bbc_title']}</h2>
<span class='desc'>{$this->lang->words['bbc_intro']}</span>
<br /><br />
<table class='ipb_table'>
	<tr class='header'>
		<th style='width: 50%'>{$this->lang->words['bbc_before']}</th>
		<th style='width: 50%'>{$this->lang->words['bbc_after']}</th>
	</tr>
	".$this->__f__80b0826ba5f5642f4b10bd61a01c478e($rows)."</table>
" . ( method_exists( $this->registry->getClass('output')->getTemplate('global'), 'include_highlighter' ) ? $this->registry->getClass('output')->getTemplate('global')->include_highlighter(1) : '' ) . "
<script type='text/javascript'>
	try {
		ipb.delegate.register('.bbc_spoiler_show', ipb.global.toggleSpoiler);
	} catch(err) { }
</script>";
return $IPBHTML;
}


function __f__80b0826ba5f5642f4b10bd61a01c478e($rows)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $rows as $row )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<tr class='subhead bar altbar'>
			<th colspan='2'>{$row['title']}</th>
		</tr>
		<tr class='row1'>
			<td class='altrow'>
				{$row['before']}
			</td>
			<td>
				{$row['after']}
			</td>
		</tr>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- emoticonPopUpList --*/
function emoticonPopUpList($editor_id, $rows) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_legends', $this->_funcHooks['emoticonPopUpList'] ) )
{
$count_2da7be791f2ffea9bce53723c2c47d33 = is_array($this->functionData['emoticonPopUpList']) ? count($this->functionData['emoticonPopUpList']) : 0;
$this->functionData['emoticonPopUpList'][$count_2da7be791f2ffea9bce53723c2c47d33]['editor_id'] = $editor_id;
$this->functionData['emoticonPopUpList'][$count_2da7be791f2ffea9bce53723c2c47d33]['rows'] = $rows;
}

if ( ! isset( $this->registry->templateStriping['emoticons'] ) ) {
$this->registry->templateStriping['emoticons'] = array( FALSE, "row1","row2");
}
$IPBHTML .= "<div class='full_emoticon'>
		<table class='ipb_table'>
			".$this->__f__acc4ecd2d2aaa33c28764d8c5f15acb8($editor_id,$rows)."		</table>
</div>";
return $IPBHTML;
}


function __f__acc4ecd2d2aaa33c28764d8c5f15acb8($editor_id, $rows)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $rows as $row )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			<tr class='" .  IPSLib::next( $this->registry->templateStriping["emoticons"] ) . "'>
				<td style='text-align: center; width: 40%;'>
					<a href=\"#\" onclick={$row['out']}ipb.editors[ {$row['in']}{$editor_id}{$row['in']} ].insert_emoticon({$row['in']}{$row['in']},\"{$row['image']}\",{$row['in']}{$row['code']}{$row['in']},{$row['in']}{$row['in']}); return false;{$row['out']} title=\"{$row['image']}\">{$row['code']}</a>
				</td>
				<td style='text-align: center; width: 60%;'>
					<a href=\"#\" onclick={$row['out']}ipb.editors[ {$row['in']}{$editor_id}{$row['in']} ].insert_emoticon({$row['in']}{$row['in']},\"{$row['image']}\",{$row['in']}{$row['code']}{$row['in']},{$row['in']}{$row['in']}); return false;{$row['out']} title=\"{$row['image']}\"><img src=\"{$this->settings['emoticons_url']}/{$row['image']}\" id='smid_{$row['smilie_id']}' alt=\"{$row['image']}\" /></a>
				</td>
			</tr>
			
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- wrap_tag --*/
function wrap_tag($tag="") {
$IPBHTML = "";
$IPBHTML .= "<div><b>{$tag}</b></div>";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>