<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Wed, 29 Aug 2012 14:15:03 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_mod_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();


}

/* -- deleteTopicForm --*/
function deleteTopicForm($forum, $topic) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- editTopicTitle --*/
function editTopicTitle($forum, $topic) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- mergeMultiplePolls --*/
function mergeMultiplePolls($polls, $tids) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- mergePostForm --*/
function mergePostForm($editor, $dates, $authors, $uploads, $seoTitle) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- mergeTopicsForm --*/
function mergeTopicsForm($forum, $topic) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- movePostForm --*/
function movePostForm($forum, $topic, $posts, $error='') {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- moveTopicForm --*/
function moveTopicForm($forum, $topic, $forum_jump) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- moveTopicsForm --*/
function moveTopicsForm($forum, $jump_html, $topics) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- pruneSplash --*/
function pruneSplash($forum="", $forums_html="", $confirm_data="", $complete_html="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- simplePage --*/
function simplePage($title="", $msg="") {
$IPBHTML = "";
$IPBHTML .= "<strong>{$title}</strong><br /> {$msg}";
return $IPBHTML;
}

/* -- softDeleteSplash --*/
function softDeleteSplash($forum, $tids=array(), $canHardDelete=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- softDeleteSplashPosts --*/
function softDeleteSplashPosts($forum, $topic, $pids=array(), $canHardDelete=false) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- splitPostForm --*/
function splitPostForm($forum, $topic, $posts, $jump) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- topicHistory --*/
function topicHistory($topic, $avg_post, $mod_logs=array()) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- unsubscribeForm --*/
function unsubscribeForm($forum, $topic, $text) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>