<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Wed, 29 Aug 2012 14:15:03 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_search_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['asForumTopics'] = array('notLastFtAsForum','topicsForumTrail','resultIsPostAsForum','isNewPostAsForum');
$this->_funcHooks['searchResults'] = array('subResult','results');
$this->_funcHooks['userPostsView'] = array('appIsSearched','appIsSearchable','apps','NPhasResults','forumsTab','membersTab','helpTab','NPTotal');


}

/* -- asForumPosts --*/
function asForumPosts($data) {
$IPBHTML = "";
$IPBHTML .= "<template>searchResultsAsPost</template>
<searchResults>
</searchResults>";
return $IPBHTML;
}

/* -- asForumTopics --*/
function asForumTopics($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['asForumTopics'] ) )
{
$count_3d3d987ff9034fc9cac12dd0ccb93c58 = is_array($this->functionData['asForumTopics']) ? count($this->functionData['asForumTopics']) : 0;
$this->functionData['asForumTopics'][$count_3d3d987ff9034fc9cac12dd0ccb93c58]['data'] = $data;
}
$IPBHTML .= "<searchResult>
	<tid>{$data['tid']}</tid>
	<title>{$data['_shortTitle']}</title>
	<state>{$data['state']}</state>
	<url>" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['type_id_2']}&amp;view=" . (($this->request['do']=='new_posts' OR $this->request['do']=='active') ? ("getnewpost") : ("" . (($data['misc']) ? ("findpost&amp;p={$data['misc']}") : ("")) . "")) . "&amp;hl={$this->request['search_higlight']}&amp;fromsearch=1", "public",'' ), "{$data['title_seo']}", "showtopic" ) . "</url>
	<authorid>{$data['author_id']}</authorid>
	<author>{$data['author_name']}</author>
	".$this->__f__07445970149631107cfa61142be3a263($data)."</searchResult>";
return $IPBHTML;
}


function __f__07445970149631107cfa61142be3a263($data)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $data['_forum_trail'] as $i => $f )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "" . (($i+1 == count( $data['_forum_trail'] )) ? ("<forum>{$f[0]}</forum>") : ("")) . "
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- followData --*/
function followData($followData) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentForumsWrapper --*/
function followedContentForumsWrapper($results) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentForumsWrapperForums --*/
function followedContentForumsWrapperForums($results) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentView --*/
function followedContentView($results, $pagination, $total, $error, $contentTypes) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- forumAdvancedSearchFilters --*/
function forumAdvancedSearchFilters($forums, $archivedPostCount=0) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- forumsVncFilters --*/
function forumsVncFilters($data, $currentPrefs) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- helpSearchResult --*/
function helpSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- memberCommentsSearchResult --*/
function memberCommentsSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- memberSearchResult --*/
function memberSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- newContentView --*/
function newContentView($results, $pagination, $total, $sortDropDown, $sortIn, $dateCutSet=0) {
$IPBHTML = "";
$IPBHTML .= "{$results}";
return $IPBHTML;
}

/* -- searchAdvancedForm --*/
function searchAdvancedForm($filters='', $msg='', $current_app, $removed_search_terms=array(), $isFT=false, $canTag=array()) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- searchResults --*/
function searchResults($results, $titlesOnly) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchResults'] ) )
{
$count_90d4afea810b2f18a297bfa201d91ce6 = is_array($this->functionData['searchResults']) ? count($this->functionData['searchResults']) : 0;
$this->functionData['searchResults'][$count_90d4afea810b2f18a297bfa201d91ce6]['results'] = $results;
$this->functionData['searchResults'][$count_90d4afea810b2f18a297bfa201d91ce6]['titlesOnly'] = $titlesOnly;
}
$IPBHTML .= "" . ((is_array( $results )) ? ("".$this->__f__85de37450ac84fdba1c4a82660b4221b($results,$titlesOnly)."		") : ("")) . "";
return $IPBHTML;
}


function __f__85de37450ac84fdba1c4a82660b4221b($results, $titlesOnly)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $results as $result )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			" . (($result['sub']) ? ("
					{$result['html']}
				
			") : ("
					{$result['html']}
				
			")) . "
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- searchResultsAsForum --*/
function searchResultsAsForum($results, $titlesOnly) {
$IPBHTML = "";
$IPBHTML .= "<template>searchResultsAsTopic</template>
<searchResults>
" . ( method_exists( $this->registry->getClass('output')->getTemplate('search'), 'searchResults' ) ? $this->registry->getClass('output')->getTemplate('search')->searchResults($results, $titlesOnly) : '' ) . "
</searchResults>";
return $IPBHTML;
}

/* -- searchResultsWrapper --*/
function searchResultsWrapper($results, $sortDropDown, $sortIn, $pagination, $total, $showing, $search_term, $url_string, $current_key, $removed_search_terms=array(), $limited=0, $wasLimited=false, $search_tags) {
$IPBHTML = "";
$IPBHTML .= "{$results}";
return $IPBHTML;
}

/* -- searchRowGenericFormat --*/
function searchRowGenericFormat($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- topicPostSearchResultAsForum --*/
function topicPostSearchResultAsForum($data, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "" . ( method_exists( $this->registry->getClass('output')->getTemplate('search'), 'asForumTopics' ) ? $this->registry->getClass('output')->getTemplate('search')->asForumTopics($data) : '' ) . "";
return $IPBHTML;
}

/* -- userPostsView --*/
function userPostsView($results, $pagination, $total, $member, $limited=0, $wasLimited=false, $beginTime=0, $sortIn=null, $sortDropDown=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['userPostsView'] ) )
{
$count_605a7e4c2e07196763121c078a2a14e5 = is_array($this->functionData['userPostsView']) ? count($this->functionData['userPostsView']) : 0;
$this->functionData['userPostsView'][$count_605a7e4c2e07196763121c078a2a14e5]['results'] = $results;
$this->functionData['userPostsView'][$count_605a7e4c2e07196763121c078a2a14e5]['pagination'] = $pagination;
$this->functionData['userPostsView'][$count_605a7e4c2e07196763121c078a2a14e5]['total'] = $total;
$this->functionData['userPostsView'][$count_605a7e4c2e07196763121c078a2a14e5]['member'] = $member;
$this->functionData['userPostsView'][$count_605a7e4c2e07196763121c078a2a14e5]['limited'] = $limited;
$this->functionData['userPostsView'][$count_605a7e4c2e07196763121c078a2a14e5]['wasLimited'] = $wasLimited;
$this->functionData['userPostsView'][$count_605a7e4c2e07196763121c078a2a14e5]['beginTime'] = $beginTime;
$this->functionData['userPostsView'][$count_605a7e4c2e07196763121c078a2a14e5]['sortIn'] = $sortIn;
$this->functionData['userPostsView'][$count_605a7e4c2e07196763121c078a2a14e5]['sortDropDown'] = $sortDropDown;
}

$datecut		= ( $this->settings['search_ucontent_days'] ) ? $this->registry->class_localization->getDate( time() - ( 86400 * intval( $this->settings['search_ucontent_days'] ) ), 'joined' ) : 0;
$IPBHTML .= "<h2 class='ipsType_pagetitle'>" . sprintf( $this->lang->words['s_participation_title'], $member['members_display_name'] ) . "</h2>
<input type='hidden' name=\"usedInJsLater\" id=\"urlString\" value=\"" . base64_encode( $this->registry->output->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;search_app={$this->request['search_app']}&amp;mid={$this->request['mid']}&amp;userMode={$this->request['userMode']}&amp;sid={$this->request['_sid']}", "public" ) ) . "\" />
" . (($total) ? ("<p class='ipsType_pagedesc'>
			" . sprintf( $this->lang->words['s_participation_msg'], $total, $member['members_display_name'] ) . "" . (($datecut) ? ("
				<span class='desc lighter'>" . sprintf( $this->lang->words['s_participation_range'], $datecut ) . "</span>
			") : ("")) . "
		</p>
	<br />") : ("")) . "
<div class='ipsLayout ipsLayout_withleft clearfix'>
	<div class='ipsLayout_left'>
		<div class='ipsBox'>
			<div class='ipsBox_container ipsSideMenu'>
				<h4>{$this->lang->words['filter_by_app']}</h4>
				<ul>
					" . ((IPSLib::appIsSearchable( 'forums', 'usercontent' )) ? ("<li " . (($this->request['search_app'] == 'forums') ? ("class='active'") : ("")) . "><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;search_app=forums&amp;mid={$this->request['mid']}&amp;userMode={$this->request['userMode']}&amp;sid={$this->request['_sid']}", "public",'' ), "", "" ) . "'>" . IPSLib::getAppTitle( 'forums' ) . "</a></li>") : ("")) . "" . ((IPSLib::appIsSearchable( 'members', 'usercontent' )) ? ("<li " . (($this->request['search_app'] == 'members') ? ("class='active'") : ("")) . "><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;search_app=members&amp;mid={$this->request['mid']}&amp;userMode={$this->request['userMode']}&amp;sid={$this->request['_sid']}", "public",'' ), "", "" ) . "'>" . IPSLib::getAppTitle( 'members' ) . "</a></li>") : ("")) . "" . ((IPSLib::appIsSearchable( 'core', 'usercontent' )) ? ("<li " . (($this->request['search_app'] == 'core') ? ("class='active'") : ("")) . "><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;search_app=core&amp;mid={$this->request['mid']}&amp;userMode={$this->request['userMode']}&amp;sid={$this->request['_sid']}", "public",'' ), "", "" ) . "'>" . IPSLib::getAppTitle( 'core' ) . "</a></li>") : ("")) . "".$this->__f__dc74ec9dd1917261d58d2a88d4ebda4c($results,$pagination,$total,$member,$limited,$wasLimited,$beginTime,$sortIn,$sortDropDown)."				</ul>
				
				" . (($this->request['search_app'] == 'forums') ? ("<h4>{$this->lang->words['userposts_morefilters']}</h4>
					<ul>
						<li " . (($this->request['userMode'] == 'all') ? ("class='active'") : ("")) . "><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;search_app={$this->request['search_app']}&amp;mid={$this->request['mid']}&amp;sid={$this->request['_sid']}&amp;search_app_filters[{$this->request['search_app']}][searchInKey]={$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}&amp;userMode=all", "public",'' ), "", "" ) . "'>{$this->lang->words['viewall_opt_dd']}</a></li>
						<li " . (($this->request['userMode'] == 'title') ? ("class='active'") : ("")) . "><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;search_app={$this->request['search_app']}&amp;mid={$this->request['mid']}&amp;sid={$this->request['_sid']}&amp;search_app_filters[{$this->request['search_app']}][searchInKey]={$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}&amp;userMode=title", "public",'' ), "", "" ) . "'>{$this->lang->words['viewallt_opt_dd']}</a></li>
						<li " . (($this->request['userMode'] == 'content') ? ("class='active'") : ("")) . "><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;search_app={$this->request['search_app']}&amp;mid={$this->request['mid']}&amp;sid={$this->request['_sid']}&amp;search_app_filters[{$this->request['search_app']}][searchInKey]={$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}&amp;userMode=content", "public",'' ), "", "" ) . "'>{$this->lang->words['viewallp_opt_dd']}</a></li>
					</ul>") : ("")) . "" . ((is_array($sortIn) AND count( $sortIn )) ? ("
					<h4>{$this->lang->words['filter_by_type']}</h4>
					<ul>
						".$this->__f__427ca8f7137036255ed4cf624bcc269d($results,$pagination,$total,$member,$limited,$wasLimited,$beginTime,$sortIn,$sortDropDown)."					</ul>
				") : ("")) . "
			</div>
		</div>
	</div>
	<div class='ipsLayout_content'>
		" . (($pagination) ? ("
			<div class='topic_controls'>
				{$pagination}
			</div>
			<br />
		") : ("")) . "
		<div class='maintitle ipsFilterbar'>
			" . ((IPSSearchRegistry::get('config.contentTypes') AND is_array( IPSSearchRegistry::get('config.contentTypes') )) ? ("" . ((count($sortDropDown)) ? ("<span class='ipsType_small'>{$this->lang->words['sort_by']}</span>&nbsp;&nbsp;
					" . ((count($sortDropDown) <= 4) ? ("
						<ul class='ipsList_inline ipsType_smaller' style='display: inline'>
							".$this->__f__df7512960998c00f90af6eacfb73a0e8($results,$pagination,$total,$member,$limited,$wasLimited,$beginTime,$sortIn,$sortDropDown)."						</ul>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					") : ("
						<ul class='ipsList_inline ipsType_smaller' style='display: inline'>
							<li class='active'>
								<a href='#' id='search_sort' class='ipbmenu'>{$sortDropDown[ $this->request['search_app_filters'][$this->request['search_app']][$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']]['sortKey'] ]} &nbsp;&nbsp;<span class='submenu_indicator'></span>&nbsp;</a>
							</li>
						</ul>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					")) . "") : ("")) . "
				<span class='ipsType_small'>{$this->lang->words['order']}</span>&nbsp;&nbsp;
				<ul class='ipsList_inline ipsType_smaller' style='display: inline'>
					<li " . (($this->request['search_app_filters'][$this->request['search_app']][$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']]['sortDir'] == 0) ? ("class='active'") : ("")) . ">
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;sid={$this->request['_sid']}&amp;mid={$this->request['mid']}&amp;userMode={$this->request['userMode']}&amp;search_app={$this->request['search_app']}&amp;search_app_filters[{$this->request['search_app']}][searchInKey]={$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}&amp;search_app_filters[{$this->request['search_app']}][{$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}][sortKey]={$this->request['search_app_filters'][$this->request['search_app']][$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']]['sortKey']}&amp;search_app_filters[{$this->request['search_app']}][{$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}][sortDir]=0", "public",'' ), "", "" ) . "'>{$this->lang->words['s_search_type_o_0']}</a>
					</li>
					<li " . (($this->request['search_app_filters'][$this->request['search_app']][$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']]['sortDir'] == 1) ? ("class='active'") : ("")) . ">
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;sid={$this->request['_sid']}&amp;mid={$this->request['mid']}&amp;userMode={$this->request['userMode']}&amp;search_app={$this->request['search_app']}&amp;search_app_filters[{$this->request['search_app']}][searchInKey]={$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}&amp;search_app_filters[{$this->request['search_app']}][{$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}][sortKey]={$this->request['search_app_filters'][$this->request['search_app']][$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']]['sortKey']}&amp;search_app_filters[{$this->request['search_app']}][{$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}][sortDir]=1", "public",'' ), "", "" ) . "'>{$this->lang->words['s_search_type_o_1']}</a>
					</li>
				</ul>") : ("" . ((count($sortDropDown)) ? ("<span class='ipsType_small'>{$this->lang->words['sort_by']}</span>&nbsp;&nbsp;
					" . ((count($sortDropDown) <= 4) ? ("
						<ul class='ipsList_inline ipsType_smaller' style='display: inline'>
							".$this->__f__d0ec7c296b1b5ca3a445a1b8499861a6($results,$pagination,$total,$member,$limited,$wasLimited,$beginTime,$sortIn,$sortDropDown)."						</ul>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					") : ("
						<ul class='ipsList_inline ipsType_smaller' style='display: inline'>
							<li class='active'>
								<a href='#' id='search_sort' class='ipbmenu'>{$sortDropDown[ $this->request['search_app_filters'][$this->request['search_app']]['sortKey'] ]} &nbsp;&nbsp;<span class='submenu_indicator'></span>&nbsp;</a>
							</li>
						</ul>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					")) . "") : ("")) . "
				<span class='ipsType_small'>{$this->lang->words['order']}</span>&nbsp;&nbsp;
				<ul class='ipsList_inline ipsType_smaller' style='display: inline'>
					<li " . (($this->request['search_app_filters'][$this->request['search_app']]['sortDir'] == 0) ? ("class='active'") : ("")) . ">
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;sid={$this->request['_sid']}&amp;mid={$this->request['mid']}&amp;userMode={$this->request['userMode']}&amp;search_app={$this->request['search_app']}&amp;search_app_filters[{$this->request['search_app']}][searchInKey]={$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}&amp;search_app_filters[{$this->request['search_app']}][sortKey]={$this->request['search_app_filters'][$this->request['search_app']]['sortKey']}&amp;search_app_filters[{$this->request['search_app']}][sortDir]=0", "public",'' ), "", "" ) . "'>{$this->lang->words['s_search_type_o_0']}</a>
					</li>
					<li " . (($this->request['search_app_filters'][$this->request['search_app']]['sortDir'] == 1) ? ("class='active'") : ("")) . ">
						<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;sid={$this->request['_sid']}&amp;mid={$this->request['mid']}&amp;userMode={$this->request['userMode']}&amp;search_app={$this->request['search_app']}&amp;search_app_filters[{$this->request['search_app']}][searchInKey]={$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}&amp;search_app_filters[{$this->request['search_app']}][sortKey]={$this->request['search_app_filters'][$this->request['search_app']]['sortKey']}&amp;search_app_filters[{$this->request['search_app']}][sortDir]=1", "public",'' ), "", "" ) . "'>{$this->lang->words['s_search_type_o_1']}</a>
					</li>
				</ul>")) . "
		</div>
		" . ((count($sortDropDown) && count($sortDropDown) >= 5) ? ("<!-- The menu for changing the sort field -->
			<ul id='search_sort_menucontent' class='ipbmenu_content with_checks' style='display: none'>
				" . ((IPSSearchRegistry::get('config.contentTypes') AND is_array( IPSSearchRegistry::get('config.contentTypes') )) ? ("".$this->__f__457e9abd15c87447e18c5a6a0b8bc054($results,$pagination,$total,$member,$limited,$wasLimited,$beginTime,$sortIn,$sortDropDown)."				") : ("".$this->__f__7823b1876c47e79622efcae48026d2f3($results,$pagination,$total,$member,$limited,$wasLimited,$beginTime,$sortIn,$sortDropDown)."				")) . "
			</ul>") : ("")) . "
		<div>
			" . (($total) ? ("
				{$results}
				<br />
				{$pagination}
			") : ("
				<p class='no_messages'>{$this->lang->words['user_posts_none']}</p>
			")) . "
		</div>
	</div>
</div>";
return $IPBHTML;
}


function __f__dc74ec9dd1917261d58d2a88d4ebda4c($results, $pagination, $total, $member, $limited=0, $wasLimited=false, $beginTime=0, $sortIn=null, $sortDropDown=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $this->registry->getApplications() as $app )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						" . ((IPSLib::appIsSearchable( $app['app_directory'], 'usercontent' ) AND !in_array( $app['app_directory'], array('core','forums','members') )) ? ("<li " . (($this->request['search_app'] == $app['app_directory']) ? ("class='active'") : ("")) . "><a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;search_app={$app['app_directory']}&amp;mid={$this->request['mid']}&amp;userMode={$this->request['userMode']}&amp;sid={$this->request['_sid']}", "public",'' ), "", "" ) . "'>" . IPSLib::getAppTitle( $app['app_directory'] ) . "</a></li>") : ("")) . "
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__427ca8f7137036255ed4cf624bcc269d($results, $pagination, $total, $member, $limited=0, $wasLimited=false, $beginTime=0, $sortIn=null, $sortDropDown=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $sortIn as $id => $_data )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
							<li " . (($this->request['search_app_filters'][$this->request['search_app']]['searchInKey'] == $_data[0]) ? ("class='active'") : ("")) . ">
								<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;search_app={$this->request['search_app']}&amp;mid={$this->request['mid']}&amp;userMode={$this->request['userMode']}&amp;sid={$this->request['_sid']}&amp;search_app_filters[{$this->request['search_app']}][searchInKey]={$_data[0]}", "public",'' ), "", "" ) . "'>{$_data[1]}</a>
							</li>
						
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__df7512960998c00f90af6eacfb73a0e8($results, $pagination, $total, $member, $limited=0, $wasLimited=false, $beginTime=0, $sortIn=null, $sortDropDown=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $sortDropDown as $k => $l )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
								<li " . (($this->request['search_app_filters'][$this->request['search_app']][$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']]['sortKey'] == $k) ? ("class='active'") : ("")) . ">
									<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;sid={$this->request['_sid']}&amp;mid={$this->request['mid']}&amp;search_app={$this->request['search_app']}&amp;userMode={$this->request['userMode']}&amp;search_app_filters[{$this->request['search_app']}][searchInKey]={$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}&amp;search_app_filters[{$this->request['search_app']}][{$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}][sortKey]={$k}&amp;search_app_filters[{$this->request['search_app']}][{$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}][sortDir]={$this->request['search_app_filters'][$this->request['search_app']][$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']]['sortDir']}", "public",'' ), "", "" ) . "'>{$l}</a>
								</li>
							
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__d0ec7c296b1b5ca3a445a1b8499861a6($results, $pagination, $total, $member, $limited=0, $wasLimited=false, $beginTime=0, $sortIn=null, $sortDropDown=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $sortDropDown as $k => $l )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
								<li " . (($this->request['search_app_filters'][$this->request['search_app']]['sortKey'] == $k) ? ("class='active'") : ("")) . ">
									<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;sid={$this->request['_sid']}&amp;mid={$this->request['mid']}&amp;userMode={$this->request['userMode']}&amp;search_app={$this->request['search_app']}&amp;search_app_filters[{$this->request['search_app']}][searchInKey]={$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}&amp;search_app_filters[{$this->request['search_app']}][sortKey]={$k}&amp;search_app_filters[{$this->request['search_app']}][sortDir]={$this->request['search_app_filters'][$this->request['search_app']]['sortDir']}", "public",'' ), "", "" ) . "'>{$l}</a>
								</li>
							
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__457e9abd15c87447e18c5a6a0b8bc054($results, $pagination, $total, $member, $limited=0, $wasLimited=false, $beginTime=0, $sortIn=null, $sortDropDown=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $sortDropDown as $k => $l )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<li " . (($this->request['search_app_filters'][$this->request['search_app']][$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']]['sortKey'] == $k) ? ("class='selected'") : ("")) . ">
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;sid={$this->request['_sid']}&amp;mid={$this->request['mid']}&amp;search_app={$this->request['search_app']}&amp;userMode={$this->request['userMode']}&amp;search_app_filters[{$this->request['search_app']}][searchInKey]={$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}&amp;search_app_filters[{$this->request['search_app']}][{$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}][sortKey]={$k}&amp;search_app_filters[{$this->request['search_app']}][{$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}][sortDir]={$this->request['search_app_filters'][$this->request['search_app']][$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']]['sortDir']}", "public",'' ), "", "" ) . "'>{$l}</a>
						</li>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

function __f__7823b1876c47e79622efcae48026d2f3($results, $pagination, $total, $member, $limited=0, $wasLimited=false, $beginTime=0, $sortIn=null, $sortDropDown=array())
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $sortDropDown as $k => $l )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
						<li " . (($this->request['search_app_filters'][$this->request['search_app']]['sortKey'] == $k) ? ("class='selected'") : ("")) . ">
							<a href='" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "app=core&amp;module=search&amp;do=user_activity&amp;sid={$this->request['_sid']}&amp;mid={$this->request['mid']}&amp;userMode={$this->request['userMode']}&amp;search_app={$this->request['search_app']}&amp;search_app_filters[{$this->request['search_app']}][searchInKey]={$this->request['search_app_filters'][$this->request['search_app']]['searchInKey']}&amp;search_app_filters[{$this->request['search_app']}][sortKey]={$k}&amp;search_app_filters[{$this->request['search_app']}][sortDir]={$this->request['search_app_filters'][$this->request['search_app']]['sortDir']}", "public",'' ), "", "" ) . "'>{$l}</a>
						</li>
					
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>