<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 18 Sep 2012 22:32:41 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'footer' => "Saludos,

El <#BOARD_NAME#> equipo.
<#BOARD_ADDRESS#>",
'header' => "",
'new_comment_on_entry' => "Hola!

Este email ha sido enviado desde: <#BOARD_NAME#>.

Un nuevo comentario ha sido hecho en <#BLOG_NAME#>.

----------------------------------
Entrada: <#ENTRY_NAME#>
Autor: <#POSTER#>
Comentario:
<#COMMENT#>
----------------------------------

El comentario puede ser encontrado aquí:
<#URL#>",
'noblog_youcan_postto' => "No tienes ningún blog en el que puedas publicar. Por favor crea uno e inténtalo de nuevo",
'send_entry_text' => "Pensé que podrías estar interesado en leer esta página del Blog: <#THE LINK#>

De,

<#USER NAME#>


",
'subject__new_comment_on_entry' => "Nuevo comentario en",
'subject__subs_new_entry' => "Rastreador de Blog de Nueva Notificación de entrada",
'subs_new_entry' => "<#NAME#>,

<#POSTER#> ha publicado una nueva entrada sin título \"<#ENTRY_NAME#>\" en el blog \"<#BLOG_NAME#>\".

----------------------------------------------------------------------
<#ENTRY#>
----------------------------------------------------------------------

La entrada puede ser encontrada aquí:
<#BOARD_ADDRESS#>?app=blog&module=display&section=blog&blogid=<#BLOG_ID#>&showentry=<#ENTRY_ID#>

Para dejar la suscripción:
--------------

Puedes dejar la suscripción en cualquier momento por loguearse en su panel de control y presionar en el enlace \"Rastreador del blog\" en la parte de \"Blog\".",
 ); 
