<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 03 Aug 2012 15:42:51 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'blog_loc_attach' => "Viendo Adjunto del Blog",
'blog_loc_blog' => "Viendo Blog",
'blog_loc_entry' => "Viendo Entrada del Blog",
'blog_loc_list' => "Viendo Blogs",
'blog_loc_post' => "Publicando una entrada o comentario",
'blog_loc_show' => "Viendo Blogs",
'blog_loc_ucp' => "Usando Panel de Control",
 ); 
