<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 14 Sep 2012 16:47:32 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'addon_help_title' => "Invision Power Chat (AddonChat) ",
'addon_invalid_key' => "Lo sentimos, esa no es una IP de Chat válida para la cuenta de ese usuiario",
'btn_continue' => "Continuar",
'enter_chatid' => "ingrese su ID de cuenta AddonChat aquí...",
'enter_siteid' => "ingresar su ID sitio aquí...",
'free_evaluation' => "Free Evaluación instantánea",
'ordered_ipchat' => "Ordenar IP Chat ?",
'own_addonchat' => "Propio AddOn Chat? ",
'para_help_title' => "Lo sentimos, esa no es una IP de Chat válida para la cuenta de ese miembro",
'para_invalid_key' => "Lo sentimos, esa no es una IP de Chat válida para la cuenta de ese miembro",
 ); 
