<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 18 Sep 2012 22:32:41 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'chat_online' => "Chatting in live chat",
'sigmachat_chatsigma' => "1",
'sigmachat_help' => "Ayuda del Chat en vivo",
'sigmachat_help_text' => "Si está ejecutando una versión de Microsoft Windows  y ve sólo un enlace de icono no accesible, tendrá que descargar una copia de la Máquina virtual de Java  para ejecutar nuestra aplicación. Puede descargar Java  Soporte para el navegador de uno de los siguientes enlaces a continuación: <br /><br />* Microsoft Virtual Machine (para MSIE) <br />* Sun Java  Plugin (para Netscape, Opera, MSIE, etc.) <br /><br />Las versiones anteriores de Netscape (en determinadas plataformas) como la v4.08, y v4.7x no podrán ejecutar el software. Recomendamos encarecidamente la actualización a una versión más reciente de Netscape (v6.xx o mejor) si éste es el caso. Algunos navegadores funcionando en plataformas Macintosh no son capaces de ejecutar el software debido a problemas fuera de nuestro control. Como WebTV no soporta Java , WebTV los usuarios no podrán acceder a las salas de chat en vivo. <br /><br />Los usuarios detrás de un cortafuegos pueden tener que contactar con sus locales de TI / administradores de red para permitir conexiones TCP en puertos 9000-9009 en client.invisionchat.com. <br /><br />Los miembros de AOL: Algunos usuarios han informado de que en el propio navegador de AOL existen dificultades para conectarse a nuestro servicio, o no se carga colores / caritas correctamente. Para resolver esto, minimizar su conexión de AOL, y utilice el navegador Internet Explorer que viene con su computadora para acceder a nuestras salas de chat.",
'sigmachat_online' => "Charlando ahora mismo en el chat",
'sigmachat_title' => "Ventana Principal del Chat en vivo",
 ); 
