<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 03 Aug 2012 15:42:51 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'antispam_branco' => "Usted no respondió a la pregunta anti-spam",
'antispam_errado' => "Usted no respondió a la pregunta anti-spam correctamente",
'assunto' => "Asunto",
'cancelar' => "Cancelar",
'captcha' => "<br /><br />Confirmar Codigo Seguridad",
'captcha_errado' => "El código de seguridad no coincide con la que se muestra!",
'cf_obrigatório' => "Usted debe llenar todos los campos",
'confirmacao_codigotransacao' => "Código de Transacción",
'confirmacao_data' => "Fecha de Pago",
'confirmacao_forma' => "Forma de Pago",
'confirmacao_IDtransacao' => "ID de Transacción",
'confirmacao_informebanco' => "-- Informe de Banco --",
'confirmacao_nr' => "Número de Documento",
'confirmacao_obs' => "Observación",
'confirmacao_valor' => "Valor Pagado",
'copia_mensagem' => "Deseo recibir una copia de este mensaje",
'departamento' => "Departamento",
'departamentos_none_admin' => "No hay foros aún vinculados a los departamentos. Por favor, informe a un administrador!",
'depemails_none_admin' => "No hay mensajes de correo electrónico vinculada a los departamentos aún. Por favor, informe a un administrador!",
'desc' => "<br /><br />Por favor, use este formulario para ponerse en contacto con los administradores del sitio. <br /><br /> NO utilice este formulario para quejarse acerca de los contenidos objetables en los foros, utilize el botón denunciar para ese tipo de reclamos. Si ya eres usuario registrado en el foro, a continuación, no te olvides de informarnos tu nombre de usuario en el foro. Si usted está teniendo problemas con su acceso, por favor, indicar con qué correo electrónico se registró.",
'done' => "Mensaje enviado",
'email' => "Su dirección Email",
'email_copiaautor' => "Esta es una copia del mensaje que envió a 
{$this->settings['board_name']}.

Enviado por: <#NOME#>
Dirección Email : <#EMAIL#>
Dirección IP: <#IP#>
Enviado el: <#DATA#>
<#CUSTOMFIELDS#>

Contenido:

<#CONTEUDO#>

Por favor, espere hasta que alguien del equipo de moderación, se ponga en contacto con usted.

Gracias.",
'email_staff' => "Enviado por: <#NOME#>
Dirección Email : <#EMAIL#>
Dirección IP: <#IP#>
Enviado el: <#DATA#>
<#CUSTOMFIELDS#>

Contenido:

<#CONTEUDO#>",
'enviado_por' => "Enviado por",
'erro_permissao' => "No está autorizado a utilizar el formulario de contacto",
'escolha_assunto' => "-- Escoja un Departamento --",
'formulario_enviado' => "Su mensaje ha sido enviado!",
'formulario_enviado_desc' => "Su mensaje ha sido enviado y el equipo de moderación de <b>{$this->settings['board_name']}</b> se dará cuenta de su contenido. Tan pronto como sea posible, alguien va a responder a su mensaje. <br /><br />Gracias por contactarnos <b>{$this->settings['board_name']}</b>. ",
'formulario_enviado_desc_emailautor' => "<br /><br />Nota: Una copia del mensaje fue enviado a tu dirección de correo electrónico.",
'mensagem' => "Ingrese su mensaje",
'mpnone_admin' => "No hay grupos seleccionados para recibir el formulario a través de MP. Informar, este error a un administrador!",
'name' => "Su Nombre",
'novo_formulario' => "Enviar Nuevo Mensaje",
'no_assunto' => "Debe ingresar un asunto!",
'no_departamento' => "Es necesario informar un departamento para enviar formulario",
'no_email' => "Debe ingresar una dirección email!",
'no_mensagem' => "Debe ingresar un mensaje!",
'no_name' => "Debe ingresar su nombre",
'ou' => "o",
'post_too_long' => "Su mensaje es demasiado largo. Por favor, vuelva atrás y acortelo a %s Kb!",
'preenchimento' => "Rellene todos los campos con el fin de ordenar el mensaje",
'short_mensagem' => "Su mensaje es demasiado corto. Usted tiene que escribir al menos 10 caracteres!",
'submit' => "Enviar Mensaje",
'systemoff' => "Zona de Contacto, no está disponible en estos momentos",
'title' => "Zona de Contacto",
'title_confirmacao' => "Confirmación de Pago",
'voltar_forum' => "Volver al Foro",
'WHERE_contato' => "Viendo Zona de Contacto",
 ); 
