<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 14 Sep 2012 16:47:32 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'choose_file' => "Escoger un Tema",
'help_back_list_title' => "Volver a la lista",
'help_read_document' => "Leer documento",
'help_return_list' => "Volver a la lista de temas",
'help_topic' => "Tema de Ayuda",
'help_topics' => "Temas de Ayuda",
'help_txt' => "Escoger un tema de la lista, o buscar un tema",
'no_help_topics' => "No hay temas de ayuda aún",
'page_title' => "Ver Temas de Ayuda",
'topic_text' => "Aquí está el tema que has escogido ver",
 ); 
