<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 18 Sep 2012 22:32:41 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'h3_title_security' => "Security Tools Available",
'sec_acp_htaccess_protection' => "ACP .htaccess protection",
'sec_change_the_line_define_cp_dire' => "Change the line: <pre>define( 'CP_DIRECTORY', '<strong>admin</strong>' );</pre> to <pre>define( 'CP_DIRECTORY', '<strong>admin_secret</strong>' );</pre>",
'sec_cp_htaccess_protection' => "ACP .htaccess protection",
'sec_executable_files' => "Executable Files",
'sec_files_55k_or_larger' => "Files 55k or larger",
'sec_file_size' => "(File Size)",
'sec_filter' => "Filter",
'sec_first_youll_need_to_physically' => "First, you'll need to physically rename the directory. Connect to your server via FTP and then browse to your IP.Board directory (this is the one that has your 				index.php file in it).",
'sec_information' => "information",
'sec_invision_power_board_can_write' => "IP.Board can write .htaccess protection into your admin directory.",
'sec_ipboard_has_a_dedicated_direct' => "IP.Board has a dedicated directory for the administration center. To further enhance security, you can rename this ACP directory.",
'sec_ipboard_is_unable_to_write_int' => "IP.Board is unable to write into your admin directory",
'sec_ipboard_security_center' => "IP.Board Security Center",
'sec_last_modified' => "Last Modified",
'sec_locate_the_admin_directory_cho' => "Locate the 'admin' directory. Choose 'rename' from your FTP client menu and rename it. For the purposes of this 				tutorial, we'll rename it 'admin_secret'.",
'sec_locate_the_initdataphp_file_th' => "Locate the 'initdata.php' file. This is in your root IP.Board folder. Download it and open it in a text editor.",
'sec_modified_in_the_past_30_days' => "Modified in the past 30 days",
'sec_near_the_top_of_this_file_youl' => "Near the top of this file, you'll see:",
'sec_password' => "Password",
'sec_please_create_a_file_called_ht' => "Please create a file called \".htpasswd\" and copy the contents below into it. Once saved, upload this new file into your 'admin' folder.",
'sec_please_create_a_file_called_ht_1' => "Please create a file called \".htaccess\" and copy the contents below into it. Once saved, upload this new file into your 'admin' folder.",
'sec_please_note' => "Please note",
'sec_proceed' => "Proceed",
'sec_renaming_the_cp_sitecontrol_di' => "Renaming the ACP \"admin\" directory",
'sec_score_5_or_more' => "Score 5 or more",
'sec_score_6_or_more' => "Score 6 or more",
'sec_score_7_or_more' => "Score 7 or more",
'sec_score_8_or_more' => "Score 8 or more",
'sec_score_9_or_more' => "Score 9 or more",
'sec_show' => "Show",
'sec_show_all' => "Show All",
'sec_step_1' => "Paso 1:",
'sec_the_security_center_is_a_centr' => "The Security Center is a centralized repository of security tools and settings.",
'sec_username' => "Username",
'sec_using_this_tool_will_overwrite' => "Using this tool will overwrite any current protection in your admin directory. You will also be required to enter the username and password immediately after saving.",
'sec_your_cp_directory_has_now_been' => "Your ACP directory has now been renamed.",
'sec_your_installation_is_checked_a' => "Your installation is checked and suggestions are made on how to improve the security of your community.",
'skin_edit_member' => "Edit",
'skin_header_admins' => "Members With ACP Access",
'skin_header_virus' => "Unauthorized File Checked Folders",
'skin_suspicious_files' => "Suspicious Files",
'skin_th_email' => "Email Address",
'skin_th_filesize' => "(File Size) &nbsp; Last Modified",
'skin_th_ip' => "IP Address",
'skin_th_name' => "Name",
'skin_th_posts' => "Posts",
'skin_th_primary_group' => "Primary Group",
'skin_th_secondary_group' => "Secondary Groups",
 ); 
