<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 03 Aug 2012 15:42:51 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'cookie__acp_mergecenter' => "Admin CP: Merge Center IDs",
'cookie__acp_mergecenter__desc' => "Set when selecting templates to merge",
'cookie__acp_sidebar' => "Admin CP: Remembers the sidebar status",
'cookie__acp_sidebar__desc' => "Set when toggling the sidebar menu open/closed",
'cookie__anonlogin' => "Anonymous Log-in",
'cookie__anonlogin__desc' => "Set if you choose to log in anonymously",
'cookie__commentmodpids' => "Selected Comment IDs (When moderating)",
'cookie__commentmodpids__desc' => "Set when selecting comments to moderate",
'cookie__coppa' => "Coppa Registration Flag",
'cookie__coppa__desc' => "Set during registration if the user identifies as under 13",
'cookie__emoticon_sidebar' => "Editor's Emoticon Bar Status",
'cookie__emoticon_sidebar__desc' => "Set when you toggle the emoticon strip open",
'cookie__guestSkinChoice' => "Guest's Skin Choice",
'cookie__guestSkinChoice__desc' => "Contains the guest's skin choice. Only used when you're not logged in and change the skin",
'cookie__ignore-license-notice' => "Adminc CP: Remembers the license notice status",
'cookie__ignore-license-notice__desc' => "Set when hiding the license expired/missing strip",
'cookie__language' => "Guest's Language Choice",
'cookie__language__desc' => "Contains the guest's language choice. Only used when you're not logged in and change the language",
'cookie__member_id' => "Member ID",
'cookie__member_id__desc' => "The member ID of the currently logged in member",
'cookie__mobileApp' => "Mobile App Flag",
'cookie__mobileApp__desc' => "Set if you're using a mobile app such as the IPS iPhone App",
'cookie__mobileBrowser' => "Mobile Browser Flag",
'cookie__mobileBrowser__desc' => "Set if you're using a mobile browser such as Safari on your iPhone",
'cookie__pass_hash' => "Member's Auto Log-in Key",
'cookie__pass_hash__desc' => "The member's MD5() auto log-in key. Used to automatically log you in",
'cookie__rteStatus' => "Editor Status",
'cookie__rteStatus__desc' => "Set when you toggle the editor between Rich Text and Standard modes",
'cookie__session_id' => "Session ID",
'cookie__session_id__desc' => "The user's MD5() session key",
'cookie__sfc' => "Last Search Time",
'cookie__sfct' => "Last Search Term",
'cookie__sfct__desc' => "Storest the contents of your last search",
'cookie__sfc__desc' => "Stores the unix time of your last search",
'cookie__uagent_bypass' => "Bypass User-agent",
'cookie__uagent_bypass__desc' => "Set if you click 'Full Version' in the mobile skin",
 ); 
