<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 14 Sep 2012 16:47:32 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'cookie_contents' => "Cookie Contents",
'cookie_header' => "Cookies",
'cookie_info_body' => "Our websites use cookies to distinguish you from other users of our websites. This helps us to provide you with a personalised experience when you browse this community.
<br />A cookie is a small file of letters and numbers that we store on your browser or the hard drive of your computer if you agree. Cookies contain information that is transferred to your computer's hard drive.
<br />Cookies are also used so that you are automatically logged back into this community. This is an option upon log-in.
<br />We never store personal information such as your name or location and we never share these cookies with third parties.
<br />To see more information on the cookies we use, please see the table below. If you have a cookie set the 'Show Contents' button is available to see what we have stored.",
'cookie_info_header' => "Cookie Information",
'cookie_protected' => "This cookie is protected as it contains sensitive log in or session information",
'core_app' => "Core",
'show_contents' => "Show Contents",
 ); 
