<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 03 Aug 2012 15:42:51 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'emailing_prefix' => "Enviando Email",
'email_details' => "Entra los detalles de email",
'email_friend' => "Usa esta característica para que un amigo conozca este tema!",
'email_member' => "Email del Usuario",
'email_recepient' => "Recipiente",
'email_sent' => "El email se ha enviado",
'email_sent_txt' => "Gracias, el email se ha enviado correctamente a ",
'err_reg_code' => "El Captcha introducido es incorrecto. Por favor, inténtalo de nuevo.",
'exceeded_flood' => "El mail no se ha podido enviar porque ya has enviado un email Entre los últimos %s minutos",
'exceeded_quota' => "El mensaje no se puede enviar porque has superado tu cupo de %s de emails por día",
'facebook_post_ok' => "El enlace se envió con éxito",
'facebook_share' => "Compartir",
'fbc_comment_desc' => "Si lo desea, puede dejar un comentario más abajo",
'fb_share_default' => "Compartir enlace con tu opinión...",
'forum_langbit' => "Foro",
'gen_error' => "No estás conectado o no puedes enviar emails",
'imp_text' => "IMPORTANTE: Para evitar la mala utilización, todos los emails enviados a través de este formulario son registrado y también los contenidos son guardados y disponibles a los administradores. NO envíes nombres de usuarios, contraseñas o cualquier detalles personal",
'member_address_title' => "Dirección de Email del Miembro",
'message' => "Mensaje",
'msg_txt' => "Nota: Usando este formulario, el receptor podrá ver tu dirección de email",
'no_message' => "Has de poner contenido para el email",
'no_subject' => "Tienes que poner un tema para el email",
'redirect' => "El email ha sido enviado",
'send_email_to' => "Enviar un email a ",
'send_lang' => "Enviar este email en",
'share_fb_name' => "Conectado a Facebook como",
'share_via_facebook' => "Compartir via Facebook",
'share_via_twitter' => "Compartir via Twitter",
'show_address_text' => "Puedes enviar a este miembro un email pulsando en el vínculo de abajo. Invision Power Board no enseña las direcciones de email en la visualización del tema para evitar que las direcciones de email sean capturadas por 'spam bots'. ",
'subject' => "Tema ",
'submit_send' => "Enviar Email ",
'title' => "Enviar una página a un amigo",
'topic_langbit' => "Tema",
'to_email' => "Enviar a (Dirección Email): ",
'to_name' => "Enviar a (Nombre de la Persona): ",
'tweet_ok' => "Tu tweet fue un éxito!",
'twitter_chrs_left' => "caracteres a la izquierda. Acortamiento de URL será automáticamente añadido",
'twitter_share' => "Compartir",
 ); 
