<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Tue, 18 Sep 2012 22:32:41 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'cookie__has_sidebar' => "Sidebar Open/Closed on Board Index",
'cookie__has_sidebar__desc' => "Set when toggling the sidebar on the board index",
'cookie__ipbforumpass_*' => "Forum Password",
'cookie__ipbforumpass_*__desc' => "Set when you enter a password for a password protected forum",
'cookie__modpids' => "Selected Post IDs (When moderating)",
'cookie__modpids__desc' => "Set when selecting posts to moderate",
'cookie__modtids' => "Selected Topic IDs (When moderating)",
'cookie__modtids__desc' => "Set when selecting topics to moderate",
'cookie__mqtids' => "Selected Post IDs (When multi-quoting)",
'cookie__mqtids__desc' => "Set when selecting posts to multi-quote",
'cookie__toggleCats' => "Category Status",
'cookie__toggleCats__desc' => "Set when toggling categories hidden/visible",
 ); 
