<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 14 Sep 2012 16:47:32 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'menu__gallery_add_global' => "Add New Global Album",
'menu__gallery_add_member' => "Add New Member Album",
'menu__gallery_album_manager' => "Album Manager",
'menu__gallery_overview' => "Overview",
'menu__gallery_settings' => "Settings",
'menu__gallery_stats' => "Stats",
'r__album_add' => "Can add albums for members?",
'r__album_delete' => "Can delete albums?",
'r__album_empty' => "Can empty albums?",
'r__album_manage' => "Can edit and resynchronize album information for members?",
'r__album_managet' => "Album Management",
'r__galstats_filealter' => "Can change file ownership?",
'r__galstats_files' => "Can run file reports?",
'r__galstats_groups' => "Can run group reports?",
'r__galstats_memberalter' => "Can change member access privileges?",
'r__galstats_members' => "Can run member reports?",
'r__stats_reports' => "Stats Reports",
 ); 
