<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 03 Aug 2012 15:42:51 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'gallery_loci_album' => "Viendo Album: ",
'gallery_loci_album_na' => "Viendo Album... ",
'gallery_loci_idx' => "Viendo Inicio Galería",
'gallery_loci_sc' => "Viendo Categoría: <#CAT#>",
'gallery_loci_sc_na' => "Viendo Categoria... ",
'gallery_loci_si' => "Viendo Imagen: ",
'gallery_loci_si_na' => "Viendo Imagen... ",
 ); 
