<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 14 Sep 2012 16:47:32 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'gateway_desc_manual_details' => "Enter any information needed to complete the transaction. For example, where to post a check.<br />You can use {id} to display the transaction ID.",
'gateway_title_2checkout_secret_word' => "Secret Word",
'gateway_title_2checkout_sid' => "Vendor Account Number",
'gateway_title_2checkout_url' => "Checkout Type",
'gateway_title_authnet_api_login' => "API Login ID",
'gateway_title_authnet_hash' => "MD5 Hash",
'gateway_title_authnet_recurring' => "Method to use for recurring payments",
'gateway_title_authnet_trans_key' => "Transaction Key",
'gateway_title_manual_details' => "Details",
'gateway_title_paypalpro_api_password' => "API Password",
'gateway_title_paypalpro_api_signature' => "API Signature",
'gateway_title_paypalpro_api_username' => "API Username",
'gateway_title_paypalpro_country' => "Your Country",
'gateway_title_paypalpro_recurring' => "Enable Recurring Payments?",
'gateway_title_paypal_api_password' => "API Password",
'gateway_title_paypal_api_signature' => "API Signature",
'gateway_title_paypal_api_username' => "API Username",
'gateway_title_paypal_email' => "PayPal Email",
'gateway_title_paypal_subscriptions' => "Enable PayPal Subscriptions Support?",
 ); 
