<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 03 Aug 2012 15:42:51 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'date_added' => "Date Added",
'highest_rated' => "Highest Rated Tutorials",
'most_viewed' => "Most Viewed Tutorials",
'no_highest_rated' => "No tutorials have been rated",
'no_most_viewed' => "No tutorials have been viewed",
'overview_title' => "Tutorials System Overview",
'quick_stats' => "Quick Statistics",
'rating' => "Rating",
'total_categories' => "Total Categories",
'total_comments' => "Total Comments",
'total_tutorials' => "Total Tutorials",
'total_views' => "Total Tutorial Views",
'tutorial' => "Tutorial",
'upgrade_date' => "Upgrade Date",
'upgrade_history' => "Upgrade History (Last 5)",
'upgrade_version' => "Version",
'views' => "Views",
 ); 
