<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Fri, 03 Aug 2012 15:42:51 +0000 by Julio César Barrera A.
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'actions' => "Acciones",
'active_users_header' => "usuario(s) activos en los ultimo %s minutos",
'add_to_favorites' => "Agregar a Favoritos",
'advanced_stats' => "Estadísticas Avanzadas",
'all_comments' => "Ver Todos los Comentarios",
'anon_members' => "usuarios anónimos(s)",
'categories' => "Categorias",
'click_to_show_opts' => "Haz clic aquí para configurar las opciones del mensaje",
'comments' => "Comentarios",
'debug_error' => "No se puede inicializar el objeto de calificación, URL no soporta votación",
'delete_article_confirm' => "¿Estás seguro que deseas eliminar este tutorial? No habrá pantallas de confirmación.",
'delete_comment_confirm' => "¿Estás seguro que deseas eliminar este comentario? No habrá pantallas de confirmación.",
'favorites_list' => "Mis Tutoriales Favoritos",
'got_post_errors' => "El siguiente error fue devuelto por classPost.php",
'guests' => "invitados(s)",
'new_tutorial' => "Publicar Nuevo Tutorial",
'no_edit_topic' => "El tema no puede ser editado",
'no_post_reply' => "La respuesta al tema no puede ser publicado",
'no_post_topic' => "El tema no puede ser publicado",
'no_view_tutorials' => "Usted no tiene permiso para ver el Sistema de Tutorías.",
'offline_title' => "(OFFLINE) ",
'pending_tutorials' => "Tutoriales Pendientes",
'random_article' => "Articulo al Azar",
'ratings' => "Puntuación",
'rating_failed' => "Hubo un error al guardar tu puntuación para este tutorial.",
'remove_from_favorites' => "Remover Favoritos",
'topic_edit_failed' => "Fallo al editar Tema",
'topic_post_failed' => "La publicación del tema falló",
'topic_reply_failed' => "La respuesta no fue publicada",
'tutorials' => "Tutoriales",
'tutorials_not_online' => "En estos momentos los Tutoriales están en mantención",
'tutorials_stats' => "Estadísticas del Sistema Tutoriales",
'views' => "Visto",
 ); 
